<script setup lang="ts">
import { shallowRef } from 'vue'
import { useI18n } from 'vue-i18n'
import InkNineSlice from '@/components/common/primitives/InkNineSlice.vue'
import CombatFidelityFrame from './CombatFidelityFrame.vue'
import CombatFidelityPortrait from './CombatFidelityPortrait.vue'
import CreationSkillSymbol from '@/components/scenes/creation/CreationSkillSymbol.vue'
import type { CombatDisplaySkill } from './combatUi'
defineProps<{ strategies: readonly { id: string; label: string }[]; selectedStrategy: string; auto: boolean; paused: boolean; skills: readonly CombatDisplaySkill[] }>()
const emit = defineEmits<{ strategy: [id: string]; auto: []; pause: []; skill: [id: string]; back: [] }>()
const { t } = useI18n()
const aiOpen = shallowRef(false)
</script>
<template>
  <div class="utility"><button class="utility-button" :aria-pressed="auto" @click="emit('auto')">{{ t(auto ? 'auto' : 'manual') }}</button><button class="utility-button pause" :aria-label="t(paused ? 'resume' : 'pause')" :aria-pressed="paused" @click="emit('pause')"><svg viewBox="0 0 24 24" aria-hidden="true"><path v-if="paused" d="M8 5 19 12 8 19Z" /><path v-else d="M7 5h3v14H7zM14 5h3v14h-3z" /></svg></button><button class="utility-button" @click="emit('back')">{{ t('back') }}</button></div>
  <div v-if="aiOpen" class="ai-panel"><InkNineSlice chrome-id="surface-m-panel" layer="surface" /><div class="ai-heading"><h2>{{ t('aiTitle') }}</h2><button class="close" :aria-label="t('closeAi')" @click="aiOpen = false">×</button></div><fieldset class="strategies"><legend>{{ t('target') }}</legend><label v-for="strategy in strategies" :key="strategy.id" :class="['strategy', { selected: selectedStrategy === strategy.id }]"><input type="radio" name="combat-preview-strategy" :value="strategy.id" :checked="selectedStrategy === strategy.id" @change="emit('strategy', strategy.id)"><span>{{ strategy.label }}</span></label></fieldset></div>
  <button v-else class="reopen utility-button" @click="aiOpen = true">{{ t('aiTitle') }}</button>
  <CombatFidelityFrame class="skill-dock" :border="32"><button v-for="skillArt in skills" :key="skillArt.id" class="skill" :aria-label="`${skillArt.label} · ${skillArt.hint}`" @click="emit('skill', skillArt.id)"><span :class="['skill-orb', skillArt.motif]"><CombatFidelityPortrait :image="skillArt.motif ? undefined : skillArt.icon"><CreationSkillSymbol v-if="skillArt.motif" :motif="skillArt.motif" /></CombatFidelityPortrait><span v-if="skillArt.badge" class="skill-badge">{{ skillArt.badge }}</span></span><span class="skill-label">{{ skillArt.label }}</span><span class="skill-tooltip"><InkNineSlice chrome-id="frame-xs-tooltip" layer="surface" /><span class="skill-tooltip__text">{{ skillArt.hint }}</span></span></button></CombatFidelityFrame>
</template>
<style scoped>
.utility { position:absolute; right:21px; top:22px; display:flex; align-items:center; gap:10px; pointer-events:auto; }.utility-button { min-height:40px; border:1px solid #b69b58; border-radius:4px; padding:5px 12px; color:#ead69f; background:#0c1616e8; font:14px var(--font-display,Georgia,serif); cursor:pointer; }.utility-button[aria-pressed="true"] { color:#ffe8a4; border-color:#e4c673; box-shadow:inset 0 0 8px #b79b4333; }.pause { width:40px; border-radius:50%; padding:8px; }.pause svg { width:100%; height:100%; fill:#e4ca83; }/* wave B chrome: surface-m-panel slice owns the AI panel shell (the old
   CombatFidelityFrame border is retired here); content stays z-index 2. */
.ai-panel { position:absolute; left:22px; top:198px; width:235px; padding:18px 17px 24px; pointer-events:auto; isolation:isolate; }.ai-panel > :not(.ink-nine-slice) { position:relative; z-index:2; }.ai-heading { display:flex; align-items:center; justify-content:space-between; border-bottom:1px solid #9e854957; margin-bottom:10px; }.ai-heading h2 { font-size:21px; font-weight:500; margin:0 0 8px; }.close { background:none; border:0; color:#c9ad66; font-size:27px; cursor:pointer; padding:0 4px; }.strategies { border:0; padding:0; margin:0; }.strategies legend { padding:0 0 10px; font-size:12px; color:#b9a880; }.strategy { display:flex; align-items:center; gap:10px; min-height:42px; margin-bottom:5px; padding:5px 7px; border:1px solid #b59a4f22; border-radius:4px; font-size:14px; cursor:pointer; color:#dacba8; background:#0002; }.strategy.selected { border-color:#d3b268; background:linear-gradient(90deg,#8b672750,#20201800); color:#ffe4a8; box-shadow:inset 0 0 8px #e4ba4b22; }.strategy input { accent-color:#be9e4c; margin:0; }.reopen { position:absolute; left:22px; top:198px; pointer-events:auto; }.skill-dock { position:absolute; right:23px; top:385px; width:133px; padding:29px 15px 24px; display:grid; gap:22px; pointer-events:auto; }.skill { position:relative; padding:0; border:0; background:none; color:#edd397; cursor:pointer; font:17px var(--font-display,Georgia,serif); }.skill-orb { position:relative; display:block; width:96px; height:96px; margin:0 auto 6px; }.skill-label { display:block; }.skill-badge { position:absolute; left:50%; top:50%; transform:translate(-50%,-50%); padding:4px 8px; background:#061116dc; border:1px solid #c3aa6b; border-radius:50%; font-size:24px; color:#f8e8be; }.skill-tooltip { display:none; position:absolute; right:118px; top:20px; width:210px; padding:12px; font-size:14px; line-height:1.5; text-align:left; }.skill-tooltip__text { position:relative; z-index:2; color:#e6d7ae; }.skill:hover .skill-tooltip,.skill:focus-visible .skill-tooltip { display:block; }.skill:hover .skill-orb { filter:drop-shadow(0 0 8px #cfb46c); }button:focus-visible { outline:2px solid #ffdf95; outline-offset:3px; }
.skill-orb.sword :deep(.portrait-content) { display:grid; place-items:center; background:radial-gradient(circle at 50% 60%,#785423,#362411 48%,#111717 76%); color:#ffe6a2; }
.skill-orb.orb :deep(.portrait-content) { display:grid; place-items:center; background:radial-gradient(circle at 50% 60%,#246d8c,#0c3048 50%,#111717 78%); color:#9de8ff; }
.skill-orb :deep(.creation-skill-symbol) { width:66px; height:66px; filter:drop-shadow(0 0 5px currentColor); }
.skill-badge { left:auto; top:auto; right:0; bottom:0; transform:none; font-size:17px; padding:2px 7px; }
</style>
