<script setup lang="ts">
import { useI18n } from 'vue-i18n'
import { resolveAssetUrl } from '@/presentation/assets/AssetBaseUrl'
import type { BodyPaperModel, BodyPaperUnit } from './bodyUi'
defineProps<{ model: BodyPaperModel; unit: BodyPaperUnit | null; notice: string }>()
const emit = defineEmits<{ invest: [] }>()
const { t } = useI18n()
const paper = resolveAssetUrl('/assets/ui/huyen-kim/scene/character-v2/paper-nine-slice.png')
</script>
<template>
  <aside class="body-paper-details"><div class="body-info-frame" :style="{borderImageSource:`url('${paper}')`}" aria-hidden="true" /><template v-if="unit"><h2>{{ unit.title }}</h2><div class="body-info-content"><p>{{ unit.description }}</p><h3>{{ t('body.gains') }}</h3><dl><div v-for="row in unit.rows" :key="row.label"><dt>{{ row.label }}</dt><dd>{{ row.value }}</dd></div><p v-if="!unit.rows.length" class="body-empty-row">{{ t('body.noGains') }}</p></dl><h3>{{ t('body.material') }}</h3><div v-for="cost in unit.costs" :key="cost.id" class="body-material" :class="{ unmet: !cost.met }"><span><img v-if="cost.icon" :src="cost.icon" alt="" class="body-cost-icon">{{ cost.name }}</span><strong>{{ cost.amountLabel }}</strong></div><p v-if="!unit.costs.length" class="body-empty-row">{{ t('body.noCost') }}</p><p v-if="unit.progressLabel" class="body-material body-progress-line"><span>{{ t('body.progress') }}</span><strong>{{ unit.progressLabel }}</strong></p><p v-for="(gate, i) in unit.gates" :key="i" class="body-gate">{{ gate }}</p><p class="body-state">{{ t(`body.state.${unit.state}`) }}</p><div v-if="model.extra" class="body-extra" :class="{ done: model.extra.done }"><div class="body-extra__head"><span>{{ model.extra.title }}</span><em>{{ model.extra.stateLabel }}</em></div><p>{{ model.extra.description }}</p><div v-if="model.extra.progressMax" class="body-extra__bar"><span :style="{ width: `${Math.min(100, (model.extra.progress ?? 0) / model.extra.progressMax * 100)}%` }" /></div><p v-if="model.extra.progressLabel" class="body-extra__count">{{ model.extra.progressLabel }}</p></div></div><button v-if="unit.actionLabel" class="body-invest" :disabled="unit.actionDisabled" @click="emit('invest')">{{ unit.actionLabel }}</button></template><template v-else><h2>{{ model.chapterLabel }}</h2><p class="body-empty-row">{{ t('body.empty') }}</p></template><p class="body-notice" role="status" aria-live="polite">{{ notice }}</p></aside>
</template>
<style scoped>
.body-paper-details { position:absolute; left:970px; top:154px; width:419px; height:575px; padding:26px 27px 12px; isolation:isolate; display:flex; flex-direction:column; }.body-info-frame { position:absolute; inset:0; z-index:-1; border:0 solid transparent; border-image-slice:300 fill; border-image-width:35px; border-image-repeat:stretch; filter:drop-shadow(0 3px 4px #79613a30); pointer-events:none; }h2 { margin:0; padding-bottom:20px; border-bottom:1px solid #ac8a46; font-size:27px; line-height:1.3; font-weight:500; }.body-info-content { flex:1; min-height:0; overflow:auto; scrollbar-width:thin; }.body-info-content > p { margin:20px 0; font-size:16px; line-height:1.7; color:#746144; }h3 { margin:23px 0 14px; padding-top:15px; border-top:1px solid #ae94554d; font-size:20px; font-weight:500; }dl { margin:0; font-size:16px; }dl > div { display:flex; justify-content:space-between; padding:9px 0; border-bottom:1px solid #ab914e22; }dd { margin:0; color:#326349; }.body-material { display:flex; justify-content:space-between; gap:12px; font-size:16px; margin:9px 0; }.body-material strong { color:#326349; font-weight:500; }.body-material.unmet strong, .body-material.unmet span { color:#8a3f2d; }.body-cost-icon { width:20px; height:20px; vertical-align:-4px; margin-right:6px; }.body-progress-line { border-top:1px dashed #ab914e55; padding-top:9px; }.body-info-content .body-state { font-size:12px; color:#927c53; }.body-gate { margin:6px 0; font-size:13px; color:#9c4f2e; }.body-empty-row { font-size:14px; color:#9a8562; font-style:italic; }.body-extra { margin-top:18px; padding:10px 12px; border:1px solid #3f7a5c88; border-radius:6px; background:#d5dec355; }.body-extra__head { display:flex; justify-content:space-between; align-items:baseline; font-size:16px; color:#2c543f; }.body-extra__head em { font-style:normal; font-size:11px; text-transform:uppercase; letter-spacing:.4px; }.body-extra p { margin:6px 0 0; font-size:13px; color:#66583d; }.body-extra__bar { margin-top:8px; height:5px; border-radius:3px; background:#c9b98b88; overflow:hidden; }.body-extra__bar span { display:block; height:100%; background:linear-gradient(90deg,#466c4b,#c6a047); }.body-extra__count { font-size:11px; }.body-invest { flex:none; height:48px; margin-top:13px; border:3px double #b4984b; border-radius:6px; background:linear-gradient(100deg,#1b513f,#35755b,#1b513f); color:#fff0c9; font:23px var(--font-display,Georgia,serif); cursor:pointer; }.body-invest:disabled { filter:grayscale(.6); opacity:.55; cursor:default; }.body-invest:focus-visible { outline:2px solid #315d48; outline-offset:3px; }.body-notice { flex:none; height:34px; padding-top:7px; margin:0; font-size:12px; line-height:14px; color:#725c38; }
</style>
