// CombatAnimationSet — per-clip metadata for combat character animation.
//
// Spec B (docs/superpowers/specs/2026-09-11-combat-animation-metadata-design.md)
// §4.2. One clip per phase of Action Playback.
//
// The clip describes a TRIMMED TEXTUREPACKER ATLAS (§3.1): frames are addressed
// by NAME, not by index into a uniform grid. That is not a preference — a
// trimmed atlas's JSON carries `sourceSize` and `spriteSourceSize` per frame,
// which is what spec C needs to plant a foot on a grid cell without guessing. A
// uniform grid pads every frame to the same box and throws that away.
//
// Every entity still shares ONE placeholder atlas today, because no character
// art is drawn yet (§3.4). What changed is that the metadata now DESCRIBES that
// atlas honestly instead of hard-coding a single global constant: when real art
// arrives, it is a TexturePacker export dropped in place plus an edit here, and
// no consumer changes.
//
// R5 (AR-24): CombatAnimationName canonical type lives in core/battle/CombatAnimationTypes.
import type { CombatAnimationName } from '@/core/battle/CombatAnimationTypes'
export type { CombatAnimationName }

/**
 * One animation clip, as a range of named frames inside an atlas.
 *
 * There is deliberately no `frameCount`: it is `lastFrame - firstFrame + 1`, and
 * two ways to state one number is the defect Spec A logged as V9.
 */
export interface CombatAnimationClip {
  /** Phaser animation key, unique per entity+name. */
  key: string

  /** Atlas texture key. Shared by every clip of one entity. */
  sheetKey: string

  /** Atlas PNG. */
  sheetUrl: string

  /** Atlas JSON, beside the PNG. */
  atlasUrl: string

  /** Frame naming, as TexturePacker emits it: `frame_` + `000` + `.png`. */
  framePrefix: string
  frameSuffix: string
  zeroPad: number

  /** Inclusive frame range within the atlas. */
  firstFrame: number
  lastFrame: number

  frameRate: number

  /** -1 = loop (idle/ready/standby), 0 = play once (cast/death). */
  repeat: number

  /**
   * The frame at which this clip's action READS as having happened — a sword
   * connecting, a palm striking. Absolute (same numbering as firstFrame), and
   * within [firstFrame, lastFrame].
   *
   * Declared here and consumed by spec D, which replaces the current
   * `ATTACK_LUNGE_DURATION_MS / 2` — half a movement tween, with no relationship
   * to the art it is timing. NOTHING IN B READS THIS. Changing playback timing
   * in the same pass as the metadata would make a regression in either
   * impossible to attribute.
   *
   * Absent on looping clips, which have no impact moment.
   */
  impactFrame?: number
}

export type CombatAnimationSet = Record<CombatAnimationName, CombatAnimationClip>

const LOOPING_NAMES = ['idle', 'ready', 'standby'] as const satisfies readonly CombatAnimationName[]
const ONE_SHOT_NAMES = ['cast', 'death'] as const satisfies readonly CombatAnimationName[]

/**
 * Declared but not iterated: the set below is written key by key so the
 * compiler checks it. This pair exists to say which names LOOP, and `satisfies`
 * keeps both halves from drifting out of `CombatAnimationName`.
 */
export const COMBAT_ANIMATION_NAMES: readonly CombatAnimationName[] = [
  ...LOOPING_NAMES,
  ...ONE_SHOT_NAMES,
]

// Placeholder atlas — one sheet shared by every entity (generated by
// scripts/generate-hon-don-tran-placeholder-art.mjs). `sheetKey` is shared;
// `key` stays per-entity. queueCombatAssets() dedupes on sheetKey, so the
// texture loads exactly once however many entities use it.
export const PLACEHOLDER_SHEET_KEY = 'combat-placeholder-32frame-sheet'
export const PLACEHOLDER_SHEET_URL = 'assets/characters/placeholder/combat-anim-32frame.png'
export const PLACEHOLDER_ATLAS_URL = 'assets/characters/placeholder/combat-anim-32frame.json'
export const PLACEHOLDER_FRAME_PREFIX = 'frame_'
export const PLACEHOLDER_FRAME_SUFFIX = '.png'
export const PLACEHOLDER_ZERO_PAD = 3
export const PLACEHOLDER_FRAME_COUNT = 32
export const PLACEHOLDER_FRAME_RATE = 8

/** The untrimmed box each placeholder frame is authored in. */
export const PLACEHOLDER_FRAME_WIDTH = 200
export const PLACEHOLDER_FRAME_HEIGHT = 350

/** Frame name for an index, matching what the generator wrote. */
export function placeholderFrameName(index: number): string {
  return `${PLACEHOLDER_FRAME_PREFIX}${String(index).padStart(PLACEHOLDER_ZERO_PAD, '0')}${PLACEHOLDER_FRAME_SUFFIX}`
}

// Single source of truth for animation key format, so CombatScene can compute a
// key without rebuilding a whole set to read one field.
export function combatAnimationKey(entityKey: string, name: CombatAnimationName): string {
  return `${entityKey}-${name}`
}

/**
 * Build the placeholder set for one entity.
 *
 * Every clip spans the whole 32-frame atlas, because the placeholder has no
 * per-phase art to carve up. That is the ONE thing here that real art changes:
 * a real entity declares a different `firstFrame`/`lastFrame` per clip, and the
 * rest of this shape already fits.
 *
 * It no longer takes a texture URL or a frame size. It used to take both,
 * `_`-prefixed and unread, while all three call sites passed real per-entity
 * values that were discarded (Spec B §2.1).
 */
export function buildPlaceholderAnimationSet(entityKey: string): CombatAnimationSet {
  const clip = (name: CombatAnimationName): CombatAnimationClip => {
    const looping = (LOOPING_NAMES as readonly CombatAnimationName[]).includes(name)

    return {
      key: combatAnimationKey(entityKey, name),
      sheetKey: PLACEHOLDER_SHEET_KEY,
      sheetUrl: PLACEHOLDER_SHEET_URL,
      atlasUrl: PLACEHOLDER_ATLAS_URL,
      framePrefix: PLACEHOLDER_FRAME_PREFIX,
      frameSuffix: PLACEHOLDER_FRAME_SUFFIX,
      zeroPad: PLACEHOLDER_ZERO_PAD,
      firstFrame: 0,
      lastFrame: PLACEHOLDER_FRAME_COUNT - 1,
      frameRate: PLACEHOLDER_FRAME_RATE,
      repeat: looping ? -1 : 0,

      // Midpoint, and honest about being arbitrary: the placeholder has no
      // moment where anything connects. Spec D re-tunes every one of these
      // against real art, and §7.1 records that no test can flag a wrong value.
      ...(looping ? {} : { impactFrame: Math.floor(PLACEHOLDER_FRAME_COUNT / 2) }),
    }
  }

  // Written out key by key ON PURPOSE, with no cast.
  //
  // The previous version ended `Object.fromEntries(entries) as CombatAnimationSet`,
  // which asserted that all of `CombatAnimationName` was present while three
  // names were not — so `set.hit` type-checked and was `undefined` at runtime
  // (Spec B §2.2). Here the compiler checks the record: add a name to
  // `CombatAnimationName` and this object stops compiling until it has a clip.
  return {
    idle: clip('idle'),
    ready: clip('ready'),
    standby: clip('standby'),
    cast: clip('cast'),
    death: clip('death'),
  }
}
