export const messages = { vi: {
  alchemy: 'Luyện Đan', forge: 'Khí Phường', companion: 'Đồng Hành', artifact: 'Pháp Bảo', vendor: 'Thương Nhân', quest: 'Nhiệm Vụ', static: 'Bản duyệt thiết kế · Dữ liệu minh họa tĩnh', tabs: 'Phân loại', material: 'Nguyên Liệu',
  recipes: 'Đan Phương', queue: 'Đan Đang Luyện', herbs: 'Dược Thảo', tuLinh: 'Tụ Linh Đan', hoiXuan: 'Hồi Xuân Đan', toCot: 'Tố Cốt Đan', tuLinhHint: 'Ngưng tụ linh khí, hỗ trợ bước đường tu hành.', selectedHerb: 'Dược thảo đã chọn', herb: 'Tử Linh Thảo', stone: 'Linh Thạch', fuel: 'Linh Mộc', ore: 'Linh Khoáng', costs: 'Nguyên Liệu Cần', duration: 'Thời Gian', outcome: 'Thành Phẩm', refinePill: 'Luyện Đan', decade: 'Mười năm',
  enhance: 'Cường Hóa', refine: 'Hóa Luyện', wash: 'Tẩy Luyện', target: 'Trang Bị Đã Chọn', sword: 'Thanh Vân Kiếm', crown: 'Đạo Quan', grade: 'Hoàng Phẩm', weapon: 'Đạo Khí', chooseEquipment: 'Chọn trang bị', preview: 'Xem Trước Thuộc Tính', current: 'Hiện Tại', next: 'Sau Cường Hóa', attack: 'Tấn Công', defense: 'Phòng Ngự', speed: 'Tốc Độ', hp: 'Sinh Lực', enhancement: 'Cường hóa +3 → +4', enhancementHint: 'Nâng cao phẩm chất chiến đấu của trang bị.',
  roster: 'Đồng Hành', feeding: 'Bồi Dưỡng', constellation: 'Mệnh Tinh', khaiSon: 'Khai Sơn Lực Sĩ', hoLy: 'Hồ Ly Tinh', linhHac: 'Linh Hạc', companionHint: 'Đồng hành bền chí trên con đường tu luyện.', realm: 'Luyện Khí · Bậc 3', artPlaceholder: 'Minh họa đồng hành đang được chuẩn bị', stats: 'Thuộc Tính', experience: 'Kinh Nghiệm', feed: 'Bồi Dưỡng', amount: 'Số Lượng',
  owned: 'Pháp Bảo Bản Mệnh', gradeTrack: 'Tiến Trình Phẩm Cấp', hoang: 'Hoàng', huyen: 'Huyền', dia: 'Địa', thien: 'Thiên', tien: 'Tiên', path: 'Đạo Lộ', nguHanh: 'Ngũ Hành Châu', artifactHint: 'Năm linh châu luân chuyển, tụ linh thành thế.', equipped: 'Đang Trang Bị', slots: 'Vị Trí Pháp Bảo', artifactLevel: 'Cấp 12', gradeUpgrade: 'Nâng Phẩm', doanBao: 'Đoán Bảo Thạch', pathAttack: 'Ngũ Hành Liên Châu', pathGuard: 'Ngũ Hành Hộ Thể', pathControl: 'Ngũ Hành Trấn Linh',
  sell: 'Bán Nguyên Liệu', selling: 'Danh Sách Vật Phẩm', unitPrice: 'Đơn Giá', quantity: 'Số Lượng', ownedAmount: 'Sở Hữu', total: 'Tổng Thu', saleSummary: 'Giao Dịch Đã Chọn', saleHint: 'Chọn nguyên liệu và số lượng muốn bán.', confirmSale: 'Bán Vật Phẩm', noEquipmentSale: 'Minh họa giao dịch nguyên liệu',
  main: 'Chính Tuyến', daily: 'Hàng Ngày', ready: 'Có Thể Nhận', mountain: 'Bước Chân Tu Hành', herbQuest: 'Thu Thập Dược Thảo', practiceQuest: 'Chuyên Cần Tu Luyện', questHint: 'Rời động phủ, khám phá núi non và tích lũy kinh nghiệm trên đường tu hành.', objectives: 'Mục Tiêu', exploreObjective: 'Hoàn thành một ải khám phá', herbObjective: 'Thu thập Tử Linh Thảo', cultivationObjective: 'Tích lũy tu vi', rewards: 'Phần Thưởng', claim: 'Nhận Thưởng', complete: 'Đã Hoàn Thành', inProgress: 'Đang Thực Hiện',
} }
