<script setup lang="ts">
import { computed, ref } from 'vue'
import { useI18n } from 'vue-i18n'
import SceneDesignCanvas from '@/components/common/SceneDesignCanvas.vue'
import PcPaperScene from '@/components/common/PcPaperScene.vue'
import PcPaperTabs from '@/components/common/PcPaperTabs.vue'
import PcPaperButton from '@/components/common/PcPaperButton.vue'
import { pcPaperResourceUrl } from '@/presentation/assets/PcPaperControls'
import { pcPaperIconUrl } from '@/presentation/assets/PcPaperIcons'
import { resolveAssetUrl } from '@/presentation/assets/AssetBaseUrl'

const { t } = useI18n()
const examples = ['alchemy', 'forge', 'companion', 'artifact', 'vendor', 'quest'] as const
type Example = typeof examples[number]
const requested = new URLSearchParams(window.location.search).get('example')
const example: Example = examples.find(id => id === requested) ?? 'alchemy'
const selectedTab = ref('')
const quantity = ref(10)
const tabIds: Record<Example, string[]> = { alchemy: ['recipes','queue','herbs'], forge: ['enhance','refine','wash'], companion: ['roster','feeding','constellation'], artifact: ['owned','path'], vendor: ['sell'], quest: ['main','daily','ready'] }
const tabs = computed(() => tabIds[example].map(id => ({ id, label: t(id) })))
const asset = (path: string) => resolveAssetUrl(`/assets/${path}`)
const art = { sword: asset('equipment/items/base-kiem/kiem-01.png'), crown: asset('equipment/items/base-quan/quan-01.png'), pearl: asset('equipment/items/base-chau/chau-05.png'), ore: asset('materials/linh_khoang.png'), fuel: asset('materials/linh_moc.png'), herb: asset('materials/herbs/tu_linh_thao/decade.png'), pill: asset('pills/tu_linh_dan.png'), healing: asset('pills/hoi_xuan_dan.png'), bonePill: asset('pills/to_cot_dan.png'), cauldron: asset('ui/huyen-kim/alchemy/alchemy-cauldron-prop@2x.png'), landscape: asset('ui/tien-hiep-2026-10/source/shared-paper-page-v1.png') }
const stats = ['hp','attack','defense','speed']
const materialRows = [{ id: 'herb', image: art.herb, amount: '12 / 5' }, { id: 'fuel', image: art.fuel, amount: '25 / 5' }]
const forgeRows = [{ id: 'ore', image: art.ore, amount: '120 / 50' }]
</script>

<template>
  <SceneDesignCanvas><PcPaperScene :title="t(example)" :navigation="false" :data-collection-craft-example="example">
    <template #tabs><PcPaperTabs :items="tabs" :selected="selectedTab || tabs[0]!.id" :label="t('tabs')" @select="selectedTab = $event" /></template>

    <div v-if="example === 'alchemy'" class="cc-alchemy">
      <section class="cc-catalog"><h2>{{ t('recipes') }}</h2><button v-for="(id,index) in ['tuLinh','hoiXuan','toCot']" :key="id" class="cc-row" :class="{ 'cc-row-selected': index === 0 }"><span class="pc-paper-slot"><img :src="[art.pill,art.healing,art.bonePill][index]" alt=""></span><span><b>{{ t(id) }}</b><small>{{ t('grade') }}</small></span></button></section>
      <section class="cc-cauldron"><h2>{{ t('tuLinh') }}</h2><p>{{ t('tuLinhHint') }}</p><img class="cc-cauldron-art" :src="art.cauldron" alt=""><div class="cc-chosen-herb"><span class="pc-paper-slot"><img :src="art.herb" alt=""></span><div><small>{{ t('selectedHerb') }}</small><b>{{ t('herb') }}</b><span>{{ t('decade') }}</span></div></div></section>
      <aside class="pc-paper-inspector cc-inspector"><h2>{{ t('tuLinh') }}</h2><p>{{ t('tuLinhHint') }}</p><h3>{{ t('costs') }}</h3><div v-for="row in materialRows" :key="row.id" class="cc-material"><span class="pc-paper-slot"><img :src="row.image" alt=""></span><span>{{ t(row.id) }}<b>{{ row.amount }}</b></span></div><dl><div><dt>{{ t('duration') }}</dt><dd>00:15:00</dd></div><div><dt>{{ t('outcome') }}</dt><dd>{{ t('tuLinh') }} × 1</dd></div></dl><PcPaperButton class="cc-cta">{{ t('refinePill') }}</PcPaperButton></aside>
    </div>

    <div v-else-if="example === 'forge'" class="cc-forge">
      <section class="cc-forge-target"><h2>{{ t('target') }}</h2><div class="cc-target-display"><span class="pc-paper-slot"><img :src="art.sword" alt=""></span><h3>{{ t('sword') }}</h3><p>{{ t('grade') }} · {{ t('weapon') }}</p><b>{{ t('enhancement') }}</b></div><h3 class="cc-rule-title">{{ t('chooseEquipment') }}</h3><div class="cc-equipment-grid"><span v-for="n in 8" :key="n" class="pc-paper-slot"><img v-if="n < 4" :src="n === 2 ? art.crown : art.sword" alt=""></span></div></section>
      <section class="cc-forge-preview"><h2>{{ t('preview') }}</h2><div class="cc-comparison-heading"><span>{{ t('current') }}</span><span>{{ t('next') }}</span></div><div v-for="(id,index) in ['attack','defense','speed']" :key="id" class="cc-comparison-row"><img :src="pcPaperIconUrl(index === 0 ? 'equipment' : 'body')" alt=""><span>{{ t(id) }}</span><b>{{ [42,8,6][index] }}</b><i>→</i><strong>{{ [48,10,7][index] }}</strong></div><p>{{ t('enhancementHint') }}</p></section>
      <aside class="pc-paper-inspector cc-inspector"><h2>{{ t('enhance') }}</h2><p>{{ t('enhancementHint') }}</p><h3>{{ t('costs') }}</h3><div v-for="row in forgeRows" :key="row.id" class="cc-material"><span class="pc-paper-slot"><img :src="row.image" alt=""></span><span>{{ t(row.id) }}<b>{{ row.amount }}</b></span></div><dl><div><dt>{{ t('stone') }}</dt><dd>500 / 120</dd></div></dl><PcPaperButton class="cc-cta">{{ t('enhance') }}</PcPaperButton></aside>
    </div>

    <div v-else-if="example === 'companion'" class="cc-companion">
      <section class="cc-catalog"><h2>{{ t('roster') }}</h2><button v-for="(id,index) in ['khaiSon','hoLy','linhHac']" :key="id" class="cc-row" :class="{ 'cc-row-selected': index === 0 }"><img class="cc-roster-icon" :src="pcPaperIconUrl('companion')" alt=""><span><b>{{ t(id) }}</b><small>{{ t('realm') }}</small></span></button></section>
      <section class="cc-companion-hero"><h2>{{ t('khaiSon') }}</h2><p>{{ t('companionHint') }}</p><div class="cc-companion-medallion"><img :src="pcPaperIconUrl('companion')" alt=""></div><small>{{ t('artPlaceholder') }}</small></section>
      <aside class="pc-paper-inspector cc-inspector"><h2>{{ t('khaiSon') }}</h2><p>{{ t('realm') }}</p><h3>{{ t('stats') }}</h3><dl><div v-for="(id,index) in stats" :key="id"><dt>{{ t(id) }}</dt><dd>{{ [360,42,18,22][index] }}</dd></div></dl><h3>{{ t('feeding') }}</h3><div class="cc-material"><span class="pc-paper-slot"><img :src="art.herb" alt=""></span><span>{{ t('herb') }}<b>12 / 1</b></span></div><div class="cc-exp"><span>{{ t('experience') }} · 240 / 500</span><progress value="240" max="500" /></div><PcPaperButton class="cc-cta">{{ t('feed') }}</PcPaperButton></aside>
    </div>

    <div v-else-if="example === 'artifact'" class="cc-artifact">
      <section class="cc-artifact-collection"><h2>{{ t('owned') }}</h2><div class="cc-artifact-card"><span class="pc-paper-slot"><img :src="art.pearl" alt=""></span><div><h3>{{ t('nguHanh') }}</h3><p>{{ t('grade') }} · {{ t('artifactLevel') }}</p><b>{{ t('grade') }}</b></div></div><h3 class="cc-rule-title">{{ t('gradeTrack') }}</h3><div class="cc-grade-track"><span v-for="(id,index) in ['hoang','huyen','dia','thien','tien']" :key="id" :class="{ current: index === 0 }"><b>{{ index + 1 }}</b>{{ t(id) }}</span></div><h3 class="cc-rule-title">{{ t('path') }}</h3><div class="cc-path-cards"><PcPaperButton v-for="(id,index) in ['pathAttack','pathGuard','pathControl']" :key="id" :variant="index ? 'secondary' : 'primary'">{{ t(id) }}</PcPaperButton></div></section>
      <aside class="pc-paper-inspector cc-inspector"><header class="cc-artifact-header"><img :src="art.pearl" alt=""><h2>{{ t('nguHanh') }}</h2></header><p>{{ t('artifactHint') }}</p><h3>{{ t('experience') }}</h3><div class="cc-exp"><span>{{ t('artifactLevel') }} · 240 / 500</span><progress value="240" max="500" /></div><h3>{{ t('gradeUpgrade') }}</h3><div class="cc-material"><span class="pc-paper-slot"><img :src="art.ore" alt=""></span><span>{{ t('doanBao') }}<b>24 / 10</b></span></div><PcPaperButton class="cc-cta">{{ t('gradeUpgrade') }}</PcPaperButton></aside>
    </div>

    <div v-else-if="example === 'vendor'" class="cc-vendor">
      <section class="cc-vendor-list"><h2>{{ t('selling') }}</h2><div class="cc-vendor-head"><span>{{ t('material') }}</span><span>{{ t('ownedAmount') }}</span><span>{{ t('unitPrice') }}</span></div><button v-for="(id,index) in ['herb','ore']" :key="id" class="cc-vendor-row" :class="{ 'cc-row-selected': index === 0 }"><span class="pc-paper-slot"><img :src="index ? art.ore : art.herb" alt=""></span><b>{{ t(id) }}</b><span>{{ [120,80][index] }}</span><strong>{{ [12,20][index] }} <img class="cc-currency" :src="pcPaperResourceUrl('jade')" :alt="t('stone')"></strong></button><p>{{ t('noEquipmentSale') }}</p></section>
      <aside class="pc-paper-inspector cc-inspector cc-sale-summary"><h2>{{ t('saleSummary') }}</h2><p>{{ t('saleHint') }}</p><div class="cc-sale-hero"><span class="pc-paper-slot"><img :src="art.herb" alt=""></span><h3>{{ t('herb') }}</h3></div><label class="cc-sale-quantity"><span>{{ t('quantity') }}</span><input v-model="quantity" type="number" min="1" max="120" :aria-label="t('quantity')"></label><dl><div><dt>{{ t('unitPrice') }}</dt><dd>12 <img class="cc-currency" :src="pcPaperResourceUrl('jade')" :alt="t('stone')"></dd></div><div><dt>{{ t('total') }}</dt><dd>{{ quantity * 12 }} <img class="cc-currency" :src="pcPaperResourceUrl('jade')" :alt="t('stone')"></dd></div></dl><PcPaperButton class="cc-cta">{{ t('confirmSale') }}</PcPaperButton></aside>
    </div>

    <div v-else class="cc-quest">
      <section class="cc-quest-list"><h2>{{ t('main') }}</h2><button v-for="(id,index) in ['mountain','herbQuest','practiceQuest']" :key="id" class="cc-quest-row" :class="{ 'cc-row-selected': index === 0 }"><img :src="pcPaperIconUrl(index ? 'quest' : 'exploration')" alt=""><span><b>{{ t(id) }}</b><small>{{ t(index ? 'inProgress' : 'complete') }}</small></span><strong>{{ ['1 / 1','3 / 5','240 / 500'][index] }}</strong></button></section>
      <aside class="pc-paper-inspector cc-inspector cc-quest-detail"><div class="cc-quest-banner" :style="{ backgroundImage: `url('${art.landscape}')` }"><h2>{{ t('mountain') }}</h2><span>{{ t('complete') }}</span></div><p>{{ t('questHint') }}</p><h3>{{ t('objectives') }}</h3><dl><div><dt>✓ {{ t('exploreObjective') }}</dt><dd>1 / 1</dd></div></dl><h3>{{ t('rewards') }}</h3><div class="cc-rewards"><div v-for="(id,index) in ['ore','tuLinh']" :key="id"><span class="pc-paper-slot"><img :src="index ? art.pill : art.ore" alt=""></span><b>{{ t(id) }}</b><small>× {{ index ? 3 : 8 }}</small></div></div><PcPaperButton class="cc-cta">{{ t('claim') }}</PcPaperButton></aside>
    </div>

    <template #footer><p class="cc-static">{{ t('static') }}</p></template>
  </PcPaperScene></SceneDesignCanvas>
</template>

<style scoped>
:global(html), :global(body), :global(#app) { margin: 0; width: 100%; height: 100%; background: #f4e7cc; }
h2 { margin: 0 0 17px; font-size: 27px; } h3 { margin: 0; font-size: 23px; } p { font-size: 17px; line-height: 1.5; }
.cc-static { color: #735a32; font-size: 13px; margin: 52px 0 0; }.cc-inspector { height: 100%; display: flex; flex-direction: column; min-height: 0; }.cc-inspector h2 { margin: 0; }.cc-inspector p { margin: 12px 0; }.cc-cta { margin-top: auto; width: 100%; font-size: 23px; }
.cc-material { display: flex; align-items: center; gap: 13px; padding: 8px 0; }.cc-material .pc-paper-slot { width: 62px; height: 62px; flex-shrink: 0; }.cc-material b { display: block; margin-top: 5px; color: #b8d591; }.cc-inspector dl { margin-top: 10px; }.cc-inspector dl > div { font-size: 17px; }
.cc-catalog { min-width: 0; }.cc-row { display: flex; align-items: center; gap: 14px; width: 100%; text-align: left; padding: 15px 8px; border: 0; border-bottom: 1px solid #b08b4d70; background: transparent; color: #302718; font: 18px var(--pc-font-body); }.cc-row .pc-paper-slot { width: 65px; height: 65px; flex-shrink: 0; }.cc-row small { display: block; color: #765d32; font-size: 14px; margin-top: 7px; }.cc-row-selected { background: linear-gradient(90deg,#d7b56844,#d7b56811); }.cc-rule-title { padding: 13px 0; margin: 20px 0 14px; border-block: 1px solid #b08b4d66; font-size: 22px; }
.cc-alchemy { display: grid; grid-template-columns: 260px minmax(0,1fr) 345px; gap: 24px; height: 100%; }.cc-cauldron { position: relative; text-align: center; }.cc-cauldron h2 { margin: 4px 0 8px; }.cc-cauldron p { margin: 0; }.cc-cauldron-art { width: 100%; height: 285px; margin-top: 20px; object-fit: contain; filter: drop-shadow(0 8px 7px #735a3233); }.cc-chosen-herb { display: flex; justify-content: center; align-items: center; gap: 13px; padding-block: 12px; border-block: 1px solid #b08b4d55; }.cc-chosen-herb .pc-paper-slot { width: 64px; height: 64px; }.cc-chosen-herb div { display: grid; gap: 4px; text-align: left; }.cc-chosen-herb small { font-size: 13px; color: #765d32; }.cc-chosen-herb b { font-size: 20px; }.cc-chosen-herb span { font-size: 15px; }
.cc-forge { display: grid; grid-template-columns: 330px minmax(0,1fr) 345px; gap: 28px; height: 100%; }.cc-forge-target h2 { text-align: center; }.cc-target-display { text-align: center; }.cc-target-display .pc-paper-slot { width: 120px; height: 120px; margin: auto auto 15px; }.cc-target-display h3 { font-size: 24px; }.cc-target-display p { margin: 8px 0; color: #765d32; }.cc-target-display > b { color: #6c7a36; font-size: 17px; }.cc-equipment-grid { display: grid; grid-template-columns: repeat(4,1fr); gap: 9px; }.cc-equipment-grid .pc-paper-slot { width: 100%; height: auto; aspect-ratio: 1; }.cc-forge-preview { padding-top: 25px; }.cc-forge-preview h2 { text-align: center; font-size: 25px; }.cc-comparison-heading { display: flex; justify-content: flex-end; gap: 35px; font-size: 15px; color: #765d32; padding: 12px 0; border-bottom: 1px solid #b08b4d77; }.cc-comparison-row { display: flex; align-items: center; gap: 10px; padding: 20px 0; font-size: 19px; border-bottom: 1px solid #b08b4d55; }.cc-comparison-row img { width: 25px; height: 25px; object-fit: contain; }.cc-comparison-row span { flex: 1; }.cc-comparison-row b { font-weight: normal; }.cc-comparison-row i { color: #967437; }.cc-comparison-row strong { color: #486a34; }.cc-forge-preview p { color: #765d32; font-size: 15px; margin-top: 25px; }
.cc-companion { height: 100%; display: grid; grid-template-columns: 270px minmax(0,1fr) 365px; gap: 25px; }.cc-roster-icon { width: 42px; height: 42px; object-fit: contain; }.cc-companion-hero { min-height: 0; overflow: hidden; text-align: center; display: flex; flex-direction: column; align-items: center; }.cc-companion-hero h2 { margin-top: 7px; }.cc-companion-hero p { margin: 0; }.cc-companion-medallion { width: 190px; height: 190px; display: grid; place-items: center; border: 3px double #b08b4d88; border-radius: 50%; background: radial-gradient(ellipse,#d8b66b22,transparent 72%); margin: auto 0 28px; }.cc-companion-medallion img { width: 90px; height: 90px; object-fit: contain; }.cc-companion-hero small { color: #765d32; font-size: 14px; margin-bottom: auto; }.cc-companion .cc-inspector h3 { margin: 10px 0 7px; padding: 8px 0; }.cc-companion .cc-inspector dl > div { padding: 7px 0; }.cc-exp { margin: 13px 0; font-size: 14px; }.cc-exp progress { display: block; width: 100%; height: 11px; accent-color: #bc964b; margin-top: 10px; }
.cc-artifact { height: 100%; display: grid; grid-template-columns: minmax(0,1.5fr) minmax(0,1fr); gap: 38px; }.cc-artifact-card { display: flex; align-items: center; gap: 25px; padding: 15px 0 25px; border-bottom: 1px solid #b08b4d66; }.cc-artifact-card .pc-paper-slot { width: 150px; height: 150px; }.cc-artifact-card h3 { font-size: 30px; }.cc-artifact-card p { color: #765d32; }.cc-artifact-card b { color: #486a34; }.cc-grade-track { display: flex; gap: 18px; justify-content: space-between; }.cc-grade-track span { display: grid; gap: 10px; text-align: center; flex: 1; color: #8b7651; font-size: 17px; }.cc-grade-track b { border-bottom: 2px solid #b08b4d55; padding-bottom: 10px; font-size: 24px; }.cc-grade-track .current { color: #302718; }.cc-grade-track .current b { border-color: #ae8537; }.cc-path-cards { display: flex; gap: 12px; }.cc-path-cards button { padding: 12px 14px; font-size: 17px; flex: 1; }.cc-artifact-header { display: flex; align-items: center; gap: 20px; justify-content: center; }.cc-artifact-header > img { width: 80px; height: 80px; object-fit: contain; }
.cc-vendor { height: 100%; display: grid; grid-template-columns: minmax(0,1.7fr) minmax(0,1fr); gap: 35px; }.cc-vendor-head { display: grid; grid-template-columns: 1fr 90px 90px; padding: 14px 20px; color: #765d32; font-size: 16px; border-block: 1px solid #b08b4d77; }.cc-vendor-row { display: flex; align-items: center; gap: 16px; width: 100%; border: 0; border-bottom: 1px solid #b08b4d55; padding: 18px 20px; color: #302718; font: 20px var(--pc-font-body); background: transparent; }.cc-vendor-row .pc-paper-slot { width: 72px; height: 72px; }.cc-vendor-row b { flex: 1; text-align: left; }.cc-vendor-row > span:not(.pc-paper-slot), .cc-vendor-row strong { width: 74px; text-align: right; font-weight: normal; }.cc-vendor-list > p { font-size: 14px; color: #765d32; }.cc-sale-hero { text-align: center; margin: 20px 0; }.cc-sale-hero .pc-paper-slot { width: 110px; height: 110px; margin: auto; }.cc-sale-hero h3 { border: 0; margin: 10px 0 0; padding: 0; }.cc-sale-quantity { display: flex; justify-content: space-between; align-items: center; margin-bottom: 10px; font-size: 19px; }.cc-sale-quantity input { width: 90px; padding: 8px 12px; background: #eeddb7; border: 1px solid #b08b4d; color: #302718; font: 19px var(--pc-font-body); }
.cc-quest { display: grid; grid-template-columns: minmax(0,1fr) minmax(0,1.3fr); gap: 35px; height: 100%; }.cc-quest-row { display: flex; align-items: center; gap: 17px; width: 100%; border: 0; border-bottom: 1px solid #b08b4d66; padding: 23px 15px; background: transparent; font: 20px var(--pc-font-body); color: #302718; }.cc-quest-row img { width: 45px; height: 45px; object-fit: contain; }.cc-quest-row > span { flex: 1; text-align: left; }.cc-quest-row small { display: block; margin-top: 10px; color: #6e793a; font-size: 15px; }.cc-quest-row strong { font-size: 17px; color: #765d32; }.cc-quest-banner { height: 95px; background-size: cover; background-position: center; position: relative; padding: 20px; flex-shrink: 0; }.cc-quest-banner h2 { color: #302718; font-size: 28px; text-align: left; }.cc-quest-banner > span { display: block; margin-top: 9px; font-size: 14px; color: #486a34; }.cc-quest-detail > p { text-align: left; }.cc-quest-detail h3 { margin: 10px 0; padding: 9px 0; }.cc-rewards { display: flex; gap: 25px; margin-bottom: 17px; justify-content: center; }.cc-rewards > div { display: grid; justify-items: center; gap: 5px; }.cc-rewards .pc-paper-slot { width: 66px; height: 66px; }.cc-rewards b { font-size: 15px; font-weight: normal; }.cc-rewards small { color: #d3b779; }
.cc-alchemy, .cc-forge, .cc-companion, .cc-artifact, .cc-vendor, .cc-quest { grid-template-rows: minmax(0,1fr); }
.cc-static { text-align: center; }
.cc-companion .cc-inspector p { margin: 8px 0; font-size: 15px; line-height: 1.3; }
.cc-companion .cc-inspector h3 { margin: 6px 0; padding: 6px 0; font-size: 18px; }
.cc-companion .cc-inspector dl > div { padding: 4px 0; font-size: 16px; line-height: 1.2; }
.cc-companion .cc-material { padding: 4px 0; }
.cc-companion .cc-material .pc-paper-slot { width: 52px; height: 52px; }
.cc-companion .cc-exp { margin: 8px 0; }
.cc-currency { display: inline-block; vertical-align: middle; width: 22px; height: 22px; object-fit: contain; }
</style>
