export const messages = {
  vi: {
    pathway: 'Đạo Lộ', fiveElements: 'Ngũ Hành', mortalWorld: 'Phàm Giới', spiritWorld: 'Linh Giới', immortalWorld: 'Tiên Giới', realmQi: 'Luyện Khí', realmFoundation: 'Trúc Cơ', realmCore: 'Kim Đan', realmSoul: 'Nguyên Anh', realmSpirit: 'Hóa Thần', realmVoid: 'Luyện Hư', realmUnion: 'Hợp Thể', realmAscendant: 'Đại Thừa', realmTier: '(Bậc 3)', realmIntro: 'Tu hành cảnh giới, khai mở tiềm năng vô tận.', achieved: 'Đã đạt', unopened: 'Chưa mở', realmProgress: 'Tiến độ tu luyện', breakthrough: 'Đột Phá', realmEffects: 'Hiệu quả cảnh giới', realmLoreTitle: 'Giới thiệu', realmLore: 'Nguyên Anh là linh hồn chân thân được hun đúc từ tinh hoa tu hành, thần thức ly thể, có thể du hành vạn dặm.', critical: 'Tỉ Lệ Bạo Kích', artifactLimit: 'Giới Hạn Pháp Bảo', fire: 'Hỏa', wood: 'Mộc', water: 'Thủy', earth: 'Thổ', metal: 'Kim', flameSlash: 'Viêm Trảm', activeSkill: 'Chủ Động', flameDescription: 'Ngưng kết nguyên hỏa, chém ra một đạo hỏa quang công kích kẻ địch phía trước.', skillEffects: 'Hiệu Quả Kỹ Năng', currentLevel: 'Hiện Tại (Lv.1)', nextLevel: 'Cấp Kế (Lv.2)', currentDamage: 'Gây 120% tấn công + 50 sát thương Hỏa.', nextDamage: 'Gây 140% tấn công + 70 sát thương Hỏa.', skillConditions: 'Điều Kiện Học/Nâng', prerequisite: 'Kỹ năng tiên quyết', none: 'Không có', requiredRealm: 'Cảnh Giới yêu cầu', fireStone: 'Hỏa Nguyên Thạch', upgrade: 'Nâng Cấp', chapters: 'Chương', chapter: 'Chương {n}', chapterName1: 'Thanh Vân Sơn', chapterName2: 'U Minh Cốc', chapterName3: 'Huyền Băng Lĩnh', chapterName4: 'Thiên Hỏa Sơn', chapterName5: 'Vạn Yêu Lâm', stage: 'Ải {n}', mapCaption: 'Chọn một ải trên bản đồ để xem thông tin.', mapDescription: 'Đường núi quanh co, linh khí hội tụ giữa núi non Thanh Vân.', stageInformation: 'Thông Tin Ải', stageProgress: 'Tiến độ', stageRewards: 'Phần Thưởng', explore: 'Khám Phá',
    graph: 'Kỹ Năng', progression: 'Cảnh Giới', list: 'Danh Sách', settings: 'Thiết Lập', crafting: 'Chế Tác', designOverview: 'Tổng Quan', designDetails: 'Chi Tiết', designHistory: 'Lịch Sử', designInspector: 'Bảng Thông Tin', designInformation: 'Thông Tin', designDescription: 'Nội dung minh họa cho bố cục và phân cấp thị giác.', designOnly: 'Bản duyệt thiết kế · Dữ liệu tĩnh', designAction: 'Hành Động', sampleNode: 'Điểm {n}', sampleRecipe: 'Công thức {n}', sampleRow: 'Mục {n}', sampleAttribute: 'Thuộc tính {n}', sampleValue: 'Mặc định', inventory: 'Kho Vật', body: 'Luyện Thể', equipment: 'Trang Bị', character: 'Tu Sĩ', realm: 'Cảnh Giới', technique: 'Công Pháp', skill: 'Kỹ Năng', bag: 'Túi', map: 'Sơn Hà Đồ',
    tabs: 'Phân loại', equipTab: 'Trang Bị', materialTab: 'Nguyên Liệu', pillTab: 'Đan Dược', all: 'Tất cả', weapon: 'Vũ Khí', crown: 'Đạo Quan', robe: 'Đạo Bào', shoes: 'Đạo Hài', ring: 'Linh Giới', pearl: 'Linh Châu',
    search: 'Tìm trang bị...', count: '2 món', sort: 'Sắp Xếp', back: 'Quay lại', meridian: 'Kinh Mạch', essence: 'Chu Thiên',
    bodyStage: 'Luyện Thể · Sơ Cấp', bodyDescription: 'Rèn luyện thể phách, cường kiện gân cốt, tăng cường căn bản tu hành.', stats: 'Thuộc Tính Tăng', costs: 'Nguyên Liệu Cần', hp: 'Sinh Lực', attack: 'Tấn Công', defense: 'Phòng Ngự', mana: 'Nội Lực', stone: 'Linh Thạch', ginseng: 'Nhân Sâm', cultivate: 'Tu Luyện', skin: 'Bì', flesh: 'Nhục', bone: 'Cốt', blood: 'Huyết', organ: 'Tạng', channels: 'Mạch', level: 'Lv.0',
    equipmentStats: 'Thuộc Tính Trang Bị', equipmentBag: 'Túi Trang Bị', enhance: 'Cường Hóa', refine: 'Hóa Luyện', detail: 'Chi Tiết', equipmentHint: 'Chọn một trang bị để xem chi tiết.', design: 'Bản duyệt thiết kế · Dữ liệu tĩnh',
  },
}
