<script setup lang="ts">
import {useI18n} from 'vue-i18n'
import EquipmentArtButton from './equipment/EquipmentArtButton.vue'
import EquipmentEnergyTube from './equipment/EquipmentEnergyTube.vue'
defineProps<{index:number;icon:string;landscape:string;level:number;running:boolean}>()
defineEmits<{toggle:[];upgrade:[]}>()
const {t}=useI18n()
</script>
<template><article class="production-source-card"><div class="source-landscape" :style="{backgroundImage:`url('${landscape}')`}"><div class="source-medallion"><img :src="icon" alt=""></div></div><div class="source-title"><h2>{{t('pp.names.'+index)}}</h2><span>{{t('pp.types.'+index)}}</span></div><div class="source-body"><p>{{t('pp.descriptions.'+index)}}</p><strong>{{t('pp.level',{level})}} · {{t('pp.next')}}</strong><EquipmentEnergyTube :fill="running?22:0" color="#6bbd92"/><small>{{t(running?'pp.working':'pp.paused')}}</small><label><input type="checkbox" :checked="running" @change="$emit('toggle')">{{t('pp.auto')}}</label><div class="source-costs"><span>{{t('pp.costWood')}}</span><span>{{t('pp.costStone')}}</span></div><EquipmentArtButton gold :disabled="level>=9" @click="$emit('upgrade')">{{t('pp.upgrade')}}</EquipmentArtButton></div></article></template>
<style scoped>
.production-source-card{min-height:0;display:flex;flex-direction:column;border:3px double #b58a42;background:#f2e4c8 url('/assets/ui/tien-hiep-2026-10/source/shared-paper-page-v1.png') center/cover;color:#30271b;box-shadow:0 1px 4px #241a1530;}.source-landscape{position:relative;flex:none;height:110px;background-position:center;background-size:cover;display:grid;place-items:center;}.source-medallion{width:78px;height:78px;display:grid;place-items:center;background:#171a15;border:3px double #c6a154;border-radius:50%;box-shadow:0 0 8px #e8bd6860;}.source-medallion img{width:62px;height:62px;object-fit:contain;}.source-title{display:flex;align-items:center;justify-content:space-between;gap:5px;padding:7px 10px;background:#24251e;color:#efdcb8;border-block:1px solid #b28a43;}.source-title h2{font:700 19px var(--pc-font-body);margin:0;}.source-title span{font-size:10px;border:1px solid #a98a52;padding:2px 6px;border-radius:8px;white-space:nowrap;}.source-body{display:flex;flex-direction:column;gap:8px;flex:1;min-height:0;padding:11px 12px;}.source-body p{margin:0;font-size:13px;line-height:1.45;min-height:40px;}.source-body strong{font-size:13px;color:#468358;font-weight:400;}.source-body small{font-size:12px;}.source-body label{display:flex;align-items:center;gap:7px;font-size:13px;}.source-body input{accent-color:#987237;width:16px;height:16px;}.source-costs{display:grid;gap:3px;color:#b74d37;font-size:12px;}.source-body button{margin-top:auto;height:37px;flex:none;font-size:16px;padding:0;}.source-body :deep(.equipment-energy-tube){flex:none;min-height:10px;}
</style>
