import { bodyMessages } from './bodyMessages'
export const remainingMessages = { vi: {
 ...bodyMessages.vi,
 preview:'BẢN DUYỆT UI · Dữ liệu mẫu', notice:'Chỉ duyệt giao diện — thao tác chưa nối gameplay.', close:'Đóng bảng', home:'Động Phủ', navigation:'Chức năng',
 defeat:{title:'Thất Bại',caption:'Đạo tâm chưa vững · Tiếp tục rèn luyện',reason:'Nguyên Nhân Thất Bại',hint:'Lực chiến hiện tại chưa đủ. Bồi dưỡng căn cơ, lĩnh ngộ kỹ năng và cường hóa trang bị trước khi khiêu chiến lại.',retry:'Thử Lại',home:'Trở Về Động Phủ'},
 rewards:'Thưởng Nhận Được', emptyRewards:'Không có vật phẩm nhận thêm.',
 inventory:{title:'Túi Đồ',all:'Tất Cả',equipment:'Trang Bị',material:'Nguyên Liệu',pill:'Đan Dược',search:'Tìm vật phẩm…',searchLabel:'Tìm vật phẩm theo tên',sort:'Sắp Xếp',use:'Sử Dụng',details:'Thông Tin Vật Phẩm',count:'{n} vật phẩm',empty:'Không có vật phẩm phù hợp.',description:'Vật phẩm thu thập trên đường tu hành. Thông tin chi tiết sẽ được cung cấp từ dữ liệu vật phẩm.',quality:'Thượng phẩm',amount:'Số lượng'},
 items:{ore:'Linh Khoáng',wood:'Linh Mộc',pill:'Tụ Linh Đan',herb:'Tụ Linh Thảo',sword:'Thanh Vân Kiếm',robe:'Huyền Vân Bào',ring:'Bích Ngọc Giới',stone:'Linh Thạch'},
 quest:{title:'Nhiệm Vụ',all:'Tất Cả',once:'Một Lần',active:'Đang Làm',ready:'Đã Hoàn Thành',claimed:'Đã Nhận',objectives:'Mục Tiêu Nhiệm Vụ',rewards:'Thưởng Nhiệm Vụ',claim:'Nhận Thưởng',follow:'Theo Dõi Nhiệm Vụ',empty:'Chưa có nhiệm vụ trong nhóm này.',description:'Theo lời chỉ dẫn của trưởng lão, lên đường tìm hiểu biến động linh khí và bồi dưỡng căn cơ.',names:{mountain:'Phong Vân Huyền Kim Sơn',herb:'Linh Dược Quý Hiếm',training:'Rèn Luyện Căn Cơ',beasts:'Trảm Yêu Trừ Ma',path:'Bước Đầu Tiên Lộ'},objective:{visit:'Đến Huyền Kim Sơn',talk:'Gặp trưởng lão',explore:'Tìm hiểu biến động linh khí'}},
 settings:{title:'Cài Đặt',group:{all:'Chung',audio:'Âm Thanh',display:'Hiển Thị',storage:'Lưu Trữ',support:'Hỗ Trợ'},audio:'Âm Thanh',display:'Hiển Thị & Ngôn Ngữ',storage:'Lưu Trữ',support:'Hỗ Trợ',master:'Âm lượng tổng',music:'Âm lượng nhạc nền',effects:'Âm lượng hiệu ứng',musicOn:'Bật nhạc nền',effectsOn:'Bật hiệu ứng âm thanh',scale:'Tỷ lệ giao diện',language:'Ngôn ngữ',motion:'Giảm chuyển động',vi:'Tiếng Việt',en:'English',save:'Lưu Trò Chơi',export:'Xuất Bản Lưu',import:'Nhập Bản Lưu',feedback:'Gửi Phản Hồi',build:'Phiên bản',buildValue:'Bản duyệt UI',storageHint:'Quản lý và sao lưu hành trình tu luyện.',supportHint:'Gửi góp ý hoặc báo lỗi để cùng hoàn thiện tiên lộ.'},
 // Mirrors the global *Preview namespaces the fidelity slot-defaults
 // resolve; keeps the preview i18n instances complete on their own.
 inventoryPreview:{title:'Túi Đồ',all:'Tất Cả',equipment:'Trang Bị',material:'Nguyên Liệu',pill:'Đan Dược',search:'Tìm kiếm',searchLabel:'Tìm trong túi đồ',sort:'Sắp Xếp',empty:'Túi đồ trống',count:'{n} món',details:'Chi Tiết',quality:'Phẩm chất',amount:'Số lượng',use:'Sử Dụng',description:'Vật phẩm thu thập trên đường tu hành. Thông tin chi tiết sẽ được cung cấp từ dữ liệu vật phẩm.'},
 questPreview:{title:'Nhiệm Vụ',all:'Tất Cả',once:'Một Lần',active:'Đang Làm',ready:'Hoàn Thành',claimed:'Đã Nhận',empty:'Chưa có nhiệm vụ',objectives:'Mục Tiêu',claim:'Nhận Thưởng',follow:'Theo Dõi',description:'Theo lời chỉ dẫn của trưởng lão, lên đường tìm hiểu biến động linh khí và bồi dưỡng căn cơ.',names:{mountain:'Phong Vân Huyền Kim Sơn',herb:'Linh Dược Quý Hiếm',training:'Rèn Luyện Căn Cơ',beasts:'Trảm Yêu Trừ Ma',path:'Bước Đầu Tiên Lộ'},objective:{visit:'Đến Huyền Kim Sơn',talk:'Gặp trưởng lão',explore:'Tìm hiểu biến động linh khí'}},
 settingsPreview:{title:'Cài Đặt',group:{all:'Chung',audio:'Âm Thanh',display:'Hiển Thị',storage:'Lưu Trữ',support:'Hỗ Trợ'},audio:'Âm Thanh',display:'Hiển Thị & Ngôn Ngữ',storage:'Lưu Trữ',storageHint:'Sao lưu và khôi phục tiến trình tu luyện.',save:'Lưu Ngay',export:'Xuất Save',import:'Nhập Save',support:'Hỗ Trợ',supportHint:'Gửi góp ý hoặc báo lỗi để cùng hoàn thiện tiên lộ.',feedback:'Gửi Phản Hồi',build:'Phiên bản',buildValue:'Bản duyệt UI',master:'Âm lượng tổng',music:'Âm lượng nhạc nền',effects:'Âm lượng hiệu ứng',musicOn:'Bật nhạc nền',effectsOn:'Bật hiệu ứng âm thanh',scale:'Tỷ lệ giao diện',language:'Ngôn ngữ',motion:'Giảm chuyển động',vi:'Tiếng Việt',en:'English'},
} } as const
