<script setup lang="ts">
import { resolveAssetUrl } from '@/presentation/assets/AssetBaseUrl'
const props = defineProps<{ kind: 'parent' | 'main' | 'sub' | 'passive'; icon: string; label: string; level: string; selected: boolean; locked: boolean }>()
const emit = defineEmits<{ select: [] }>()
const frameUrl = (kind: typeof props.kind) => resolveAssetUrl(`/assets/ui/tien-hiep-2026-10/controls/skill-node-${kind}-v1.png`)
</script>
<template><button type="button" class="skill-art-node" :class="[`skill-art-node--${kind}`, { selected, locked }]" :aria-pressed="selected" :aria-label="label" :data-node-kind="kind" @click="emit('select')"><span class="skill-art-node__medal"><img class="skill-art-node__icon" :src="icon" alt=""><img class="skill-art-node__frame" :src="frameUrl(kind)" alt=""></span><b>{{ label }}</b><small>{{ level }}</small></button></template>
<style scoped>
.skill-art-node {--node-size:60px;display:grid;justify-items:center;gap:4px;width:110px;padding:0;border:0;background:transparent;color:#372719;cursor:pointer;font:14px var(--pc-font-body);}.skill-art-node--parent {--node-size:78px;}.skill-art-node--main {--node-size:70px;}.skill-art-node--passive {--node-size:66px;}.skill-art-node__medal {position:relative;width:var(--node-size);height:var(--node-size);display:grid;place-items:center;}.skill-art-node__medal::before {content:'';position:absolute;inset:16%;border-radius:50%;background:#1c231e;}.skill-art-node__icon {position:absolute;width:58%;height:58%;object-fit:contain;border-radius:50%;}.skill-art-node__frame {position:absolute;inset:0;width:100%;height:100%;object-fit:contain;transition:filter 150ms ease,transform 150ms ease;pointer-events:none;}.skill-art-node:not(.locked):hover .skill-art-node__frame {filter:brightness(1.15) drop-shadow(0 0 3px #d8ab55);transform:scale(1.035);}.skill-art-node.selected .skill-art-node__frame {filter:brightness(1.2) drop-shadow(0 0 5px #ffd17a) drop-shadow(0 0 8px #d4983d70);}.skill-art-node:not(.locked):active .skill-art-node__medal {transform:scale(.96);}.skill-art-node.locked .skill-art-node__medal {filter:grayscale(.9);opacity:.6;}.skill-art-node.locked:hover .skill-art-node__frame {filter:brightness(1.12);}.skill-art-node:focus-visible {outline:1px solid #ac843e;outline-offset:4px;border-radius:8px;}.skill-art-node small {font-size:12px;}@media(prefers-reduced-motion:reduce){.skill-art-node__frame {transition:none;}}
</style>
