<script setup lang="ts">
import {useI18n} from 'vue-i18n'
import ForgeFidelityWorkspace from './ForgeFidelityWorkspace.vue'
export interface ForgeItemDisplay{id:string;name:string;icon:string}
defineProps<{mode:string;items:readonly ForgeItemDisplay[];item:ForgeItemDisplay}>()
const emit=defineEmits<{mode:[id:string];select:[id:string];action:[request:{mode:string;itemId:string;kind:string}]}>()
const {t}=useI18n()
const modes=['enhance','wash','refine','dissolve','decompose']
</script>
<template><div class="forge-scene"><nav class="forge-tabs"><button v-for="id in modes" :key="id" :aria-pressed="id===mode" @click="emit('mode',id)">{{t(`forge.${id}`)}}</button></nav><div class="forge-layout"><aside class="selection"><h2>{{t('forge.select')}}</h2><button v-for="entry in items" :key="entry.id" :aria-pressed="item.id===entry.id" @click="emit('select',entry.id)"><img :src="entry.icon" alt=""><span>{{entry.name}}<small>{{t('forge.grade')}}</small></span><b>+12</b></button><p>{{t('forge.bagHint')}}</p></aside><ForgeFidelityWorkspace :mode="mode" :item="item" @action="emit('action',{mode,itemId:item.id,kind:$event})"/></div></div></template>
<style scoped>
.forge-scene{height:100%;font-family:var(--font-display,Georgia,serif);color:#493720}.forge-tabs{display:flex;gap:10px;border-bottom:1px solid #91724377;height:43px;margin-bottom:17px}.forge-tabs button,.forge-tabs a{padding:7px 23px;border:0;border-bottom:3px solid transparent;background:transparent;color:#72532e;text-decoration:none;font:700 17px var(--font-display,Georgia,serif);cursor:pointer}.forge-tabs button[aria-pressed=true]{color:#28533c;border-color:#957035;background:#9c813c16}.forge-layout{display:grid;grid-template-columns:258px 1fr;gap:26px;height:399px}.selection{padding-right:19px;border-right:1px solid #92734166}.selection h2{font-size:18px;margin:0 0 15px}.selection button{display:flex;align-items:center;gap:10px;width:100%;height:83px;margin-bottom:13px;padding:9px;border:1px solid #977344;background:#7652250c;color:#503a22;text-align:left;cursor:pointer}.selection button[aria-pressed=true]{background:linear-gradient(110deg,#284731,#11271c);color:#f5dfac;border-color:#b59961;box-shadow:inset 0 0 0 3px #c4a66833}.selection img{width:56px;height:56px;object-fit:contain;filter:drop-shadow(0 2px 4px #0007)}.selection span{font-size:15px;font-weight:700}.selection small{display:block;font-size:11px;font-weight:400;margin-top:7px}.selection b{margin-left:auto;color:#bd9650;font-size:13px}.selection p{font-size:12px;line-height:1.7;color:#756142;margin:16px 0 10px}.selection a{color:#305c42;font-size:13px}.forge-tabs button:focus-visible,.selection button:focus-visible{outline:2px solid #9a763e;outline-offset:3px}
</style>
