<script setup lang="ts">
import {computed,shallowRef,watch} from 'vue'
import {useI18n} from 'vue-i18n'
import {resolveAssetUrl} from '@/presentation/assets/AssetBaseUrl'
import type {ForgeItemDisplay} from './ForgeFidelityScene.vue'
const props=defineProps<{mode:string;item:ForgeItemDisplay;compact?:boolean}>()
const emit=defineEmits<{action:[kind:string]}>()
const {t}=useI18n()
const locked=shallowRef<readonly string[]>([])
watch(()=>[props.mode,props.item.id],()=>{locked.value=[]})
const destructive=computed(()=>props.mode==='dissolve'||props.mode==='decompose')
const rows=computed(()=>['attack','defense','spirit','critical'].map((id,i)=>({id,before:['1.260','840','320','8,5%'][i],after:['1.386','924','352','9,3%'][i]})))
function toggle(id:string){locked.value=locked.value.includes(id)?locked.value.filter(value=>value!==id):[...locked.value,id]}
</script>
<template><section class="workspace" :class="{compact}"><div class="upper"><div class="focus-item" aria-hidden="true"><img class="furnace-art" :src="resolveAssetUrl('/assets/ui/huyen-kim/scene/forge-v2/furnace-v1.png')" alt=""></div><div class="comparison"><p class="chosen-item">{{item.name}}</p><h3>{{t(destructive?'forge.output':'forge.comparison')}}</h3><p class="explanation">{{t(`forge.hint.${mode}`)}}</p><template v-if="!destructive"><div class="column-head"><span>{{t('forge.stat')}}</span><span>{{t('forge.before')}}</span><span>{{t('forge.after')}}</span></div><div v-for="row in rows" :key="row.id" class="stat-row"><span>{{t(`forge.${row.id}`)}}</span><b>{{row.before}}</b><strong>{{locked.includes(row.id)?row.before:row.after}}</strong><button v-if="mode==='wash'||mode==='refine'" class="lock" :aria-label="t('forge.lock',{name:t(`forge.${row.id}`)})" :aria-pressed="locked.includes(row.id)" @click="toggle(row.id)">{{locked.includes(row.id)?'◆':'◇'}}</button></div></template><div v-else class="outputs"><div v-for="(asset,i) in ['/assets/materials/linh_khoang.png','/assets/materials/linh_moc.png']" :key="asset"><img :src="resolveAssetUrl(asset)" alt=""><b>{{t(i===0?'items.ore':'items.wood')}}</b><span>× {{i===0?'8':'12'}}</span></div></div></div></div><footer><div class="cost"><h3>{{t(destructive?'forge.warning':'forge.cost')}}</h3><p v-if="destructive">{{t('forge.destructiveHint')}}</p><div v-else><img :src="resolveAssetUrl('/assets/materials/linh_khoang.png')" alt=""><span>{{t('items.ore')}} <b>8 / 12</b></span><span class="stone">{{t('items.stone')}} <b>1.280 / 8.640</b></span></div></div><div class="actions"><button v-if="mode==='wash'||mode==='refine'" class="preview" @click="emit('action','preview')">{{t('forge.preview')}}</button><button class="submit" :class="{danger:destructive}" @click="emit('action','submit')">{{t(`forge.${mode}`)}}</button></div></footer></section></template>
<style scoped>
.workspace{height:399px;display:flex;flex-direction:column;gap:19px}.upper{display:grid;grid-template-columns:227px 1fr;gap:26px;min-height:278px}.focus-item{height:278px;text-align:center;padding:23px 20px;border:0 solid transparent;border-image-slice:360 fill;border-image-width:27px;color:#f5dfa9;filter:drop-shadow(0 4px 7px #31200d44)}.mode-name{font-size:14px;letter-spacing:3px;color:#bdac80}.focus-item img{display:block;width:113px;height:113px;object-fit:contain;margin:10px auto;filter:drop-shadow(0 4px 7px #000)}.focus-item h2{font-size:21px;margin:0}.focus-item p{font-size:12px;color:#a2c5a7;margin:8px 0}.stamp{display:block;color:#b7974b;font-size:18px}.comparison h3,.cost h3{font-size:18px;margin:0 0 10px;border-bottom:1px solid #95753f66;padding-bottom:9px}.explanation{font-size:13px;line-height:1.7;color:#77603b;margin:0 0 13px;min-height:44px}.column-head,.stat-row{display:grid;grid-template-columns:1.2fr 1fr 1fr 27px;align-items:center;gap:14px}.column-head{font-size:12px;color:#806b43;padding-bottom:8px}.stat-row{height:35px;font-size:14px;border-bottom:1px solid #a2874833}.stat-row b{font-weight:400;color:#645337}.stat-row strong{color:#2f7550}.lock{border:1px solid #a08551;background:transparent;color:#7a6133;width:25px;height:25px;cursor:pointer}.lock[aria-pressed=true]{background:#284431;color:#f5d996}.outputs{display:flex;gap:22px;justify-content:center;margin-top:12px}.outputs>div{display:flex;align-items:center;flex-direction:column;gap:7px;font-size:14px}.outputs img{height:95px;width:95px;object-fit:contain;background:radial-gradient(#365343,#10271c);border:1px solid #b69858;padding:8px;box-shadow:inset 0 0 0 3px #b29a5144}.outputs span{color:#2f7050}.workspace footer{display:flex;align-items:center;gap:20px;border-top:1px solid #95753f66;padding-top:12px;min-height:85px}.cost{flex:1}.cost h3{border:0;padding:0;margin-bottom:8px;font-size:16px}.cost>div{display:flex;align-items:center;gap:10px;font-size:12px}.cost img{width:35px;height:35px;object-fit:contain}.cost b{color:#34644a;margin-left:5px}.stone{margin-left:12px}.cost p{font-size:13px;line-height:1.7;color:#913c2c;margin:0;max-width:390px}.actions{display:flex;gap:10px}.actions button{height:43px;padding:0 22px;font:700 17px var(--font-display,Georgia,serif);border:1px solid #ab884c;cursor:pointer}.submit{background:linear-gradient(#35563e,#13291c);color:#f7e0a3}.preview{background:#d9bc7855;color:#62421d}.submit.danger{background:linear-gradient(#844b34,#47281f);color:#f5d5a1}.actions button:hover{filter:brightness(1.15)}button:focus-visible{outline:2px solid #9b733d;outline-offset:3px}
.workspace.compact{height:415px;gap:12px}.compact .upper{grid-template-columns:164px 1fr;gap:17px;min-height:265px}.compact .focus-item{height:265px;padding:23px 14px}.compact .focus-item img{width:95px;height:95px}.compact .focus-item h2{font-size:17px}.compact .comparison h3{font-size:16px}.compact .explanation{font-size:12px}.compact .stat-row{font-size:12px;gap:7px;height:33px}.compact .column-head{font-size:11px;gap:7px}.compact footer{flex-wrap:wrap;gap:8px;min-height:125px}.compact .cost{flex-basis:100%}.compact .actions{margin-left:auto}.compact .outputs{gap:16px}.compact .outputs img{width:76px;height:76px}.compact .outputs b{font-size:12px}
.focus-item .furnace-art{height:150px;width:150px;margin:2px auto 8px}.compact .focus-item .furnace-art{height:147px;width:130px;margin:2px auto 7px}.focus-item p{margin:5px 0}.stamp{display:none}
.workspace{position:relative;isolation:isolate}.upper{position:relative;grid-template-columns:1fr}.focus-item{position:absolute;inset:0;pointer-events:none;border-image:none!important;filter:none;padding:0;height:100%;color:#634522;text-align:left;z-index:-1}.focus-item .mode-name,.focus-item h2,.focus-item p{display:none}.focus-item .furnace-art{position:absolute;left:5px;top:0;width:225px;height:278px;margin:0;opacity:.87;object-fit:contain;filter:drop-shadow(0 4px 7px #61451d33)}.comparison{margin-left:250px}.compact .upper{grid-template-columns:1fr}.compact .focus-item{inset:0;height:100%;padding:0}.compact .focus-item .furnace-art{left:-9px;top:-4px;width:195px;height:273px;margin:0;opacity:.87}.compact .comparison{margin-left:181px}
.chosen-item{margin:0 0 9px;font-size:17px;font-weight:700;color:#624721}.compact .chosen-item{font-size:15px;margin-bottom:8px}.compact .explanation{margin-bottom:7px;min-height:35px}.compact .stat-row{height:30px}
</style>
