// ReactionDefinition.ts -- authored reaction catalog entry (contract
// sec.81 + spec sec.61). Immutable data; the registry validates the whole
// set at seal (megaplan M1 step 1). Payoff steps are DATA (CON-23 -- no
// engine-side per-reaction branches); M4 populates the emitters.
//
// Element DIRECTION comes from the relation fields, never cast order:
// sinh {parent -> child}; khac {attacker -> defender}.

import type { ElementType } from '../element/ElementType'
import type { BuffDefinitionId } from '../battle/contracts/ids'
import type {
  ReactionId,
  ReactionParticipantRole,
  ReactionRelation,
} from './ReactionTypes'

export interface ReactionElementRelation {
  parent?: ElementType    // sinh only
  child?: ElementType     // sinh only
  attacker?: ElementType  // khac only
  defender?: ElementType  // khac only
}

import { type StackExpr } from './StackExpr'
export type { StackExpr } from './StackExpr'

/** Payoff steps (contract sec.44 ordering + spec sec.77-78 shapes).
    Authored ordered steps; consume ops are generated by the resolver,
    NOT authored here. */
export type ReactionPayoffStep =
  | { kind: 'add_child_stacks'; stacks: StackExpr }                       // sinh conversion -> AddBuffStacksOperation (NOT ApplyBuff -- contract sec.75)
  | { kind: 'add_child_modifier'; modifierId: string; channel: 'potency' | 'periodic_damage'; value: StackExpr }
      // emits AddBuffModifierOperation { operation:'multiply', reapply:'max', lifetime:{type:'buff_lifetime'} }
  | { kind: 'extend_child_duration'; turns: StackExpr; maxRemaining: number } // ExtendBuffDurationOperation, authored cap (spec sec.37)
  | { kind: 'reaction_damage'; coefficient: StackExpr; damageProfile: string; element: 'attacker' } // DealDamageOperation origin.kind 'reaction', canCrit:false (R-A)
  | { kind: 'apply_status'; definitionId: BuffDefinitionId; stacks?: StackExpr; durationOverride?: StackExpr;
      maxDuration?: number; modifier?: { modifierId: string; channel: 'potency'; value: StackExpr };
      when?: { role: ReactionParticipantRole; op: 'gte' | 'lt'; value: number } } // -> ApplyBuffOperation(reactionEligibility:'suppressed')
  | { kind: 'push_gauge'; fractionOfMax: StackExpr }                      // PushGaugeOperation -- negative = pushback
  | { kind: 'heal_from_damage'; fraction: StackExpr; capRatio: number; healTarget: 'source' }
      // DeferredOperation after the damage op; ratio capped at resolution (R-B)

export interface ReactionPayoffDefinition {
  /** Authored ordered payoff steps -- M4 emits ops in this order after
      the generated consume ops (contract sec.44). */
  readonly steps: readonly ReactionPayoffStep[]
}

export interface ReactionDefinition {
  readonly id: ReactionId
  readonly relation: ReactionRelation
  /** Authored, UNIQUE within the registry -- tie-break level 3 (contract
      sec.33). Never id-derived. */
  readonly selectionTiePriority: number
  readonly elements: ReactionElementRelation
  readonly payoff: ReactionPayoffDefinition
}
