// CombatPresentationCatalogue — what each combat entity's art actually IS.
//
// Spec B §3.3/§4.4
// (docs/superpowers/specs/2026-09-11-combat-animation-metadata-design.md).
//
// Hand-written TypeScript beside the profile, not a generated manifest — it
// follows `PlayerVisualProfiles.ts`, which is already a reviewed catalogue and
// already carries `combatSourceSize` and `NormalizedBodyAnchor`.
//
// The honest trade (§3.3): frame counts can drift from the art, because nothing
// here measures the file. `tests/architecture/atlasFramesExist.test.ts` exists
// specifically to make that drift fail a test rather than a frame, and §7.1
// records what it cannot catch.
//
// ENTITY_ART_MODE (locked 2026-09-19): every entity declares BOTH forms -
// a static PNG + idle motion, and an animated clip set - and the catalogue
// emits the one the mode selects. Uniformity is enforced by construction and
// by tests/architecture/artModeUniformity.test.ts: no entry may ship a `kind`
// different from the mode, and unregistered entities resolve to the shared
// `entity-placeholder` entry of the SAME kind rather than to a Rectangle.
import { PLAYER_VISUAL_PROFILES } from './PlayerVisualProfiles'
import {
  ENEMY_SOURCE_SIZE,
  enemyTextureUrl,
  resolveEnemyTextureKey,
  MORTAL_ENEMY_TEMPLATE_IDS,
} from '@/game/support/EnemyArt'
import { ENTITY_ART_MODE } from './EntityArtMode'
import {
  combatAnimationKey,
  type ArtExtent,
  type AtlasClip,
  type CombatAnimationCatalogue,
  type CombatAnimationName,
  type CombatEntityPresentation,
  type IdleMotion,
  type StaticEntityArt,
} from './CombatEntityPresentation'

// ---------------------------------------------------------------------------
// Player atlas and placeholder fallbacks
// ---------------------------------------------------------------------------
//
// The mortal profile uses the real trimmed atlas below. Profiles without
// dedicated art retain the shared placeholder until their own sheet is
// authored. `sheetKey` is shared within one atlas while the animation `key`
// stays per-entity; `queueCombatAssets()` dedupes the sheet load.
export const PLACEHOLDER_SHEET_KEY = 'combat-placeholder-32frame-sheet'
export const PLACEHOLDER_SHEET_URL = 'assets/characters/placeholder/combat-anim-32frame.png'
export const PLACEHOLDER_ATLAS_URL = 'assets/characters/placeholder/combat-anim-32frame.json'
export const PLACEHOLDER_FRAME_PREFIX = 'frame_'
export const PLACEHOLDER_FRAME_SUFFIX = '.png'
export const PLACEHOLDER_ZERO_PAD = 3
export const PLACEHOLDER_FRAME_COUNT = 32
export const PLACEHOLDER_FRAME_RATE = 8

/** The untrimmed box each placeholder frame is authored in. */
export const PLACEHOLDER_FRAME_WIDTH = 200
export const PLACEHOLDER_FRAME_HEIGHT = 350

/**
 * The placeholder figure's own box inside the 200x350 authored frame, as
 * fractions, taken from the tallest frame the generator emits.
 *
 * Checked against the atlas JSON by tests/architecture/artExtentDeclared.test.ts,
 * so regenerating the art with different margins fails a test rather than
 * silently resizing every character (Spec C §2.3).
 */
export const PLACEHOLDER_EXTENT_X = 0.28
export const PLACEHOLDER_EXTENT_Y = 0.0943
export const PLACEHOLDER_EXTENT_W = 0.44
export const PLACEHOLDER_EXTENT_H = 0.7943

// ---------------------------------------------------------------------------
// Static-mode placeholder - the shared silhouette every unregistered entity
// draws while ENTITY_ART_MODE === 'static'. Generated by
// scripts/generate-entity-placeholder.mjs; the uniformity rule is that
// "no art" still renders SOMETHING of the active mode's kind.
// ---------------------------------------------------------------------------
export const PLACEHOLDER_ENTITY_KEY = 'entity-placeholder'
export const PLACEHOLDER_STATIC_TEXTURE_KEY = 'entity-placeholder'
export const PLACEHOLDER_STATIC_TEXTURE_URL =
  'assets/characters/placeholder/entity-placeholder.png'
export const PLACEHOLDER_STATIC_SOURCE_SIZE = { w: 128, h: 128 } as const

/**
 * Alpha-bbox extents of the static PNGs, as fractions of each source box -
 * measured by scripts/measure-entity-extents.mjs (opaqueBounds, same as
 * pack-mortal-combat-art.mjs). Painted art has real margins: `{0,0,1,1}`
 * would oversize the figure. Re-run the script when a PNG changes.
 */
export const PLAYER_STATIC_EXTENT_MORTAL: ArtExtent = {
  x: 0,
  y: 0,
  w: 0.946646,
  h: 0.98749,
}
export const PLAYER_STATIC_EXTENT_PHAP_TU: ArtExtent = {
  x: 0.061872,
  y: 0,
  w: 0.843001,
  h: 0.985197,
}
export const PLACEHOLDER_STATIC_EXTENT: ArtExtent = {
  x: 0.226563,
  y: 0.140625,
  w: 0.546875,
  h: 0.78125,
}

const PLAYER_STATIC_EXTENTS: Record<string, ArtExtent> = {
  'player-mortal-ink-sword-concept-v2': PLAYER_STATIC_EXTENT_MORTAL,
  'player-phap-tu-v1': PLAYER_STATIC_EXTENT_PHAP_TU,
}

export const PLAYER_MORTAL_ATLAS_SHEET_KEY = 'player-mortal-combat-atlas-v2'
export const PLAYER_MORTAL_ATLAS_SHEET_URL =
  'assets/characters/player/mortal/player-mortal-combat-atlas-v2.png'
export const PLAYER_MORTAL_ATLAS_URL =
  'assets/characters/player/mortal/player-mortal-combat-atlas-v2.json'
export const PLAYER_MORTAL_FRAME_PREFIX = 'frame_'
export const PLAYER_MORTAL_FRAME_SUFFIX = '.png'
export const PLAYER_MORTAL_ZERO_PAD = 3
export const PLAYER_MORTAL_SOURCE_WIDTH = 128
export const PLAYER_MORTAL_SOURCE_HEIGHT = 128

const PLAYER_MORTAL_IDLE_EXTENT = { x: 0.203125, y: 0.0625, w: 0.6328125, h: 0.8671875 }
const PLAYER_MORTAL_STANDBY_EXTENT = { x: 0.203125, y: 0.0625, w: 0.6328125, h: 0.8671875 }
const PLAYER_MORTAL_DEATH_EXTENT = { x: 0.2109375, y: 0.0625, w: 0.609375, h: 0.8671875 }

/** Frame name for an index, matching what the generator wrote. */
export function placeholderFrameName(index: number): string {
  return `${PLACEHOLDER_FRAME_PREFIX}${String(index).padStart(PLACEHOLDER_ZERO_PAD, '0')}${PLACEHOLDER_FRAME_SUFFIX}`
}

/** Frame name for an index inside ANY atlas clip's naming scheme. */
export function atlasFrameName(clip: AtlasClip, index: number): string {
  return `${clip.framePrefix}${String(index).padStart(clip.zeroPad, '0')}${clip.frameSuffix}`
}

function playerMortalClip(
  entityKey: string,
  name: CombatAnimationName,
  firstFrame: number,
  lastFrame: number,
  frameRate: number,
  extent: AtlasClip['extent'],
  repeat: number,
): AtlasClip {
  return {
    key: combatAnimationKey(entityKey, name),
    sheetKey: PLAYER_MORTAL_ATLAS_SHEET_KEY,
    sheetUrl: PLAYER_MORTAL_ATLAS_SHEET_URL,
    atlasUrl: PLAYER_MORTAL_ATLAS_URL,
    framePrefix: PLAYER_MORTAL_FRAME_PREFIX,
    frameSuffix: PLAYER_MORTAL_FRAME_SUFFIX,
    zeroPad: PLAYER_MORTAL_ZERO_PAD,
    firstFrame,
    lastFrame,
    frameRate,
    sourceSize: {
      w: PLAYER_MORTAL_SOURCE_WIDTH,
      h: PLAYER_MORTAL_SOURCE_HEIGHT,
    },
    extent,
    repeat,
  }
}

/**
 * The mortal v2 atlas under the uniform contract (2026-09-19). Attack frames
 * (43-90: cast/sweep_hand/punch) and the old `ready` loop still exist in the
 * sheet but are dead art - the contract is idle/standby/death, and attacks
 * read through the shared lunge tween. No transition clips exist yet, so the
 * entity snaps between loops like every placeholder does.
 */
function playerMortalCatalogue(entityKey: string): CombatAnimationCatalogue {
  return {
    idle: playerMortalClip(entityKey, 'idle', 0, 31, 8, PLAYER_MORTAL_IDLE_EXTENT, -1),
    standby: playerMortalClip(entityKey, 'standby', 32, 42, 8, PLAYER_MORTAL_STANDBY_EXTENT, -1),
    death: playerMortalClip(entityKey, 'death', 91, 106, 10, PLAYER_MORTAL_DEATH_EXTENT, 0),
  }
}

/**
 * Which clip names MUST exist on every animated entity - the three combat
 * states. `COMBAT_ANIMATION_NAMES` additionally lists the optional ones
 * (transitions, cultivate) so tests can check "every declared key is a real
 * name" in both directions.
 */
export const REQUIRED_COMBAT_ANIMATION_NAMES = [
  'idle',
  'standby',
  'death',
] as const satisfies readonly CombatAnimationName[]

export const COMBAT_ANIMATION_NAMES: readonly CombatAnimationName[] = [
  ...REQUIRED_COMBAT_ANIMATION_NAMES,
  'idle_to_standby',
  'standby_to_idle',
  'cultivate',
]

/**
 * Shared-placeholder clips span the 32-frame sheet for every clip - the
 * placeholder has no authored states, so all three loops play the same
 * figure. No transition clips: an unauthored transition would freeze the
 * sprite for its full duration, which reads worse than the snap the
 * playback fallback produces.
 */
function placeholderClips(entityKey: string): CombatAnimationCatalogue {
  const clip = (name: CombatAnimationName): AtlasClip => ({
    key: combatAnimationKey(entityKey, name),
    sheetKey: PLACEHOLDER_SHEET_KEY,
    sheetUrl: PLACEHOLDER_SHEET_URL,
    atlasUrl: PLACEHOLDER_ATLAS_URL,
    framePrefix: PLACEHOLDER_FRAME_PREFIX,
    frameSuffix: PLACEHOLDER_FRAME_SUFFIX,
    zeroPad: PLACEHOLDER_ZERO_PAD,
    firstFrame: 0,
    lastFrame: PLACEHOLDER_FRAME_COUNT - 1,
    frameRate: PLACEHOLDER_FRAME_RATE,
    sourceSize: { w: PLACEHOLDER_FRAME_WIDTH, h: PLACEHOLDER_FRAME_HEIGHT },
    extent: {
      x: PLACEHOLDER_EXTENT_X,
      y: PLACEHOLDER_EXTENT_Y,
      w: PLACEHOLDER_EXTENT_W,
      h: PLACEHOLDER_EXTENT_H,
    },
    repeat: name === 'death' ? 0 : -1,
  })

  return {
    idle: clip('idle'),
    standby: clip('standby'),
    death: clip('death'),
  }
}

// ---------------------------------------------------------------------------
// Static entities
// ---------------------------------------------------------------------------

/**
 * Peak bob, in SCREEN pixels. Small on purpose: this reads as breathing, not as
 * hovering. Not scaled by projection depth — see `IdleMotion.amplitudePx`.
 */
export const ENEMY_IDLE_AMPLITUDE_PX = 6

/** Base cycle. The jitter below spreads entities around it. */
const ENEMY_IDLE_BASE_PERIOD_MS = 2200

/** How far an entity's period may stray from the base, in ms, either way. */
const ENEMY_IDLE_PERIOD_JITTER_MS = 600

/**
 * Deterministic per-key jitter.
 *
 * Random would do the job on screen and be untestable; this is data, derived
 * from the key, so a test can assert that two different enemies do NOT share a
 * period. Without it a row of five wolves breathes as one organism, which reads
 * worse than not breathing at all.
 */
function idleMotionFor(entityKey: string): IdleMotion {
  let hash = 0

  for (let index = 0; index < entityKey.length; index++) {
    hash = (hash * 31 + entityKey.charCodeAt(index)) % 100000
  }

  const spread = (hash / 100000) * 2 - 1

  return {
    amplitudePx: ENEMY_IDLE_AMPLITUDE_PX,
    periodMs: Math.round(ENEMY_IDLE_BASE_PERIOD_MS + spread * ENEMY_IDLE_PERIOD_JITTER_MS),
  }
}

// ---------------------------------------------------------------------------
// The catalogue
// ---------------------------------------------------------------------------

/**
 * Fallback player entity key — same PNG as the mortal profile, different key.
 * Used when `combat-grid-view.ts` does not find the current profile's texture
 * loaded yet.
 *
 * Declared HERE rather than imported from `CombatPreload`: that module imports
 * this one, and the reverse edge would be a cycle.
 */
export const FALLBACK_PLAYER_ENTITY_KEY = 'player-mortal'

/**
 * Both declared forms of one entity, side by side. The catalogue emits ONE
 * of them - picked by ENTITY_ART_MODE - and keeps the other reachable through
 * `animatedArtFormFor`/`staticArtFormFor` so the dormant form's data stays
 * honest (the atlas/extent tests validate it against files on disk in
 * EITHER mode).
 */
function entityPresentation(
  staticArt: { texture: StaticEntityArt; idleMotion: IdleMotion },
  clips: CombatAnimationCatalogue,
): CombatEntityPresentation {
  return ENTITY_ART_MODE === 'animated'
    ? { kind: 'animated', clips }
    : { kind: 'static', texture: staticArt.texture, idleMotion: staticArt.idleMotion }
}

function buildCatalogue(): {
  entries: Map<string, CombatEntityPresentation>
  animatedForms: Map<string, CombatAnimationCatalogue>
  staticForms: Map<string, { texture: StaticEntityArt; idleMotion: IdleMotion }>
} {
  const animatedForms = new Map<string, CombatAnimationCatalogue>()
  const staticForms = new Map<string, { texture: StaticEntityArt; idleMotion: IdleMotion }>()

  const register = (
    entityKey: string,
    texture: StaticEntityArt,
    clips: CombatAnimationCatalogue,
  ): void => {
    animatedForms.set(entityKey, clips)
    staticForms.set(entityKey, { texture, idleMotion: idleMotionFor(entityKey) })
  }

  // Every player profile. Profiles sharing the mortal PNG (kiem_tu, the_tu)
  // collapse onto the mortal key - same art either way.
  for (const profile of Object.values(PLAYER_VISUAL_PROFILES)) {
    register(
      profile.combatTextureKey,
      {
        textureKey: profile.combatTextureKey,
        textureUrl: profile.combatTextureUrl.replace(/^\/+/, ''),
        sourceSize: { ...profile.combatSourceSize },
        extent:
          PLAYER_STATIC_EXTENTS[profile.combatTextureKey] ?? PLAYER_STATIC_EXTENT_MORTAL,
      },
      profile.combatTextureKey === PLAYER_VISUAL_PROFILES.mortal.combatTextureKey
        ? playerMortalCatalogue(profile.combatTextureKey)
        : placeholderClips(profile.combatTextureKey),
    )
  }

  register(
    FALLBACK_PLAYER_ENTITY_KEY,
    {
      textureKey: FALLBACK_PLAYER_ENTITY_KEY,
      textureUrl: PLAYER_VISUAL_PROFILES.mortal.combatTextureUrl.replace(/^\/+/, ''),
      sourceSize: { ...PLAYER_VISUAL_PROFILES.mortal.combatSourceSize },
      extent: PLAYER_STATIC_EXTENT_MORTAL,
    },
    playerMortalCatalogue(FALLBACK_PLAYER_ENTITY_KEY),
  )

  // Enemies are still images plus a bob in 'static' mode, placeholder clips
  // in 'animated' mode until their sheets are drawn.
  for (const templateId of MORTAL_ENEMY_TEMPLATE_IDS) {
    const textureKey = resolveEnemyTextureKey(templateId)

    if (!textureKey) {
      continue
    }

    register(
      textureKey,
      {
        textureKey,
        textureUrl: enemyTextureUrl(textureKey),
        sourceSize: { ...ENEMY_SOURCE_SIZE },
        // The Mortal PNGs are untrimmed: the animal fills its own file.
        extent: { x: 0, y: 0, w: 1, h: 1 },
      },
      placeholderClips(textureKey),
    )
  }

  // The wildcard entry - every spawnable entity without authored art resolves
  // to this at the resolution layer (entityAnimationKeyPrefix,
  // getOrCreateSprite), so "missing art" renders the SAME kind as everything
  // else instead of a Rectangle. Rectangle stays only for the double-fallback
  // where even the placeholder texture failed to load.
  register(
    PLACEHOLDER_ENTITY_KEY,
    {
      textureKey: PLACEHOLDER_STATIC_TEXTURE_KEY,
      textureUrl: PLACEHOLDER_STATIC_TEXTURE_URL,
      sourceSize: { ...PLACEHOLDER_STATIC_SOURCE_SIZE },
      extent: PLACEHOLDER_STATIC_EXTENT,
    },
    placeholderClips(PLACEHOLDER_ENTITY_KEY),
  )

  const entries = new Map<string, CombatEntityPresentation>()

  for (const entityKey of animatedForms.keys()) {
    const staticArt = staticForms.get(entityKey)
    const clips = animatedForms.get(entityKey)

    // register() sets both maps together - a missing half is a build bug,
    // not a reachable state.
    if (!staticArt || !clips) {
      continue
    }

    entries.set(entityKey, entityPresentation(staticArt, clips))
  }

  return { entries, animatedForms, staticForms }
}

const { entries: CATALOGUE, animatedForms: ANIMATED_FORMS, staticForms: STATIC_FORMS } =
  buildCatalogue()

/** Every entity key the catalogue knows. For the guards, and for preload. */
export function combatPresentationEntityKeys(): readonly string[] {
  return [...CATALOGUE.keys()]
}

/**
 * One function, one answer per entity - the form ENTITY_ART_MODE selected.
 *
 * `undefined` for an entity with no drawn art at all - a realm whose enemies
 * are not in the Mortal batch, or a test fixture. Callers that need "every
 * entity renders something" resolve `PLACEHOLDER_ENTITY_KEY` instead.
 */
export function presentationFor(entityKey: string): CombatEntityPresentation | undefined {
  return CATALOGUE.get(entityKey)
}

/**
 * The entity's ANIMATED form, whatever the mode emitted. Clip metadata exists
 * even while 'static' is active - the atlas/extent tests validate it against
 * the files on disk so the day the mode flips, the data is already honest.
 */
export function animatedArtFormFor(entityKey: string): CombatAnimationCatalogue | undefined {
  return ANIMATED_FORMS.get(entityKey)
}

/** The entity's STATIC form, whatever the mode emitted. See animatedArtFormFor. */
export function staticArtFormFor(
  entityKey: string,
): { texture: StaticEntityArt; idleMotion: IdleMotion } | undefined {
  return STATIC_FORMS.get(entityKey)
}

/**
 * Registered entity keys still pointing at placeholder art - derived, not
 * declared, so the answer cannot drift from the catalogue. In 'static' mode
 * the check is the silhouette texture key; in 'animated' mode the shared
 * sheet. This is the placeholder-art debt list; the ratchet guard is
 * tests/architecture/artPlaceholderDebt.test.ts (shrink freely, never grow).
 */
export function placeholderEntityKeys(): readonly string[] {
  const keys: string[] = []

  for (const [entityKey, presentation] of CATALOGUE) {
    if (entityKey === PLACEHOLDER_ENTITY_KEY) {
      continue
    }

    if (presentation.kind === 'animated') {
      const clips = Object.values(presentation.clips)

      if (clips.every((clip) => clip.sheetKey === PLACEHOLDER_SHEET_KEY)) {
        keys.push(entityKey)
      }
    } else if (presentation.texture.textureKey === PLACEHOLDER_STATIC_TEXTURE_KEY) {
      keys.push(entityKey)
    }
  }

  return keys
}

/** Every animated entity's clips, for preload and animation registration. */
export function animatedCombatEntities(): Array<{
  entityKey: string
  clips: CombatAnimationCatalogue
}> {
  const animated: Array<{ entityKey: string; clips: CombatAnimationCatalogue }> = []

  for (const [entityKey, presentation] of CATALOGUE) {
    if (presentation.kind === 'animated') {
      animated.push({ entityKey, clips: presentation.clips })
    }
  }

  return animated
}
