// CombatPresentationCatalogue — what each combat entity's art actually IS.
//
// Spec B §3.3/§4.4
// (docs/superpowers/specs/2026-09-11-combat-animation-metadata-design.md).
//
// Hand-written TypeScript beside the profile, not a generated manifest — it
// follows `PlayerVisualProfiles.ts`, which is already a reviewed catalogue and
// already carries `combatSourceSize` and `NormalizedBodyAnchor`.
//
// The honest trade (§3.3): frame counts can drift from the art, because nothing
// here measures the file. `tests/architecture/atlasFramesExist.test.ts` exists
// specifically to make that drift fail a test rather than a frame, and §7.1
// records what it cannot catch.
//
// THIS ANSWERS FROM WHAT HAS BEEN DRAWN, NEVER FROM `artTierFor`. The tier is an
// expectation checked in a test; letting it influence what a scene resolves at
// runtime would mean a boss without art resolving to something that does not
// exist.
import { PLAYER_VISUAL_PROFILES } from './PlayerVisualProfiles'
import { ENEMY_SOURCE_SIZE, enemyTextureUrl, resolveEnemyTextureKey } from '@/game/support/EnemyArt'
import {
  combatAnimationKey,
  type AtlasClip,
  type CombatAnimationCatalogue,
  type CombatAnimationName,
  type CombatEntityPresentation,
  type IdleMotion,
} from './CombatEntityPresentation'

// ---------------------------------------------------------------------------
// The placeholder atlas
// ---------------------------------------------------------------------------
//
// ONE sheet, shared by every animated entity, generated by
// `scripts/generate-hon-don-tran-placeholder-art.mjs`. `sheetKey` is shared;
// the animation `key` stays per-entity, so two entities on one texture still
// animate independently. `queueCombatAssets()` dedupes on sheetKey, so the
// texture loads exactly once however many entities use it.
//
// Every character asset in this project is still a placeholder (§3.4) —
// backgrounds are the only drawn art. That does NOT weaken this catalogue: what
// it buys is per-entity metadata that describes its art HONESTLY, which is what
// C and D are blocked on. When real art lands it is a TexturePacker export
// dropped in place plus an edit to the entry below.
export const PLACEHOLDER_SHEET_KEY = 'combat-placeholder-32frame-sheet'
export const PLACEHOLDER_SHEET_URL = 'assets/characters/placeholder/combat-anim-32frame.png'
export const PLACEHOLDER_ATLAS_URL = 'assets/characters/placeholder/combat-anim-32frame.json'
export const PLACEHOLDER_FRAME_PREFIX = 'frame_'
export const PLACEHOLDER_FRAME_SUFFIX = '.png'
export const PLACEHOLDER_ZERO_PAD = 3
export const PLACEHOLDER_FRAME_COUNT = 32
export const PLACEHOLDER_FRAME_RATE = 8

/** The untrimmed box each placeholder frame is authored in. */
export const PLACEHOLDER_FRAME_WIDTH = 200
export const PLACEHOLDER_FRAME_HEIGHT = 350

/** Frame name for an index, matching what the generator wrote. */
export function placeholderFrameName(index: number): string {
  return `${PLACEHOLDER_FRAME_PREFIX}${String(index).padStart(PLACEHOLDER_ZERO_PAD, '0')}${PLACEHOLDER_FRAME_SUFFIX}`
}

const LOOPING_NAMES = ['idle', 'ready', 'standby'] as const satisfies readonly CombatAnimationName[]
const ONE_SHOT_NAMES = ['cast', 'death'] as const satisfies readonly CombatAnimationName[]

/**
 * Declared but not iterated when building a catalogue: the record below is
 * written key by key so the COMPILER checks it. This pair exists to say which
 * names loop, and `satisfies` keeps both halves from drifting out of
 * `CombatAnimationName`.
 */
export const COMBAT_ANIMATION_NAMES: readonly CombatAnimationName[] = [
  ...LOOPING_NAMES,
  ...ONE_SHOT_NAMES,
]

/**
 * Every clip spans the whole 32-frame placeholder, because the placeholder has
 * no per-phase art to carve up. That is the ONE thing real art changes: a real
 * entity declares a different `firstFrame`/`lastFrame` per clip, and the rest of
 * this shape already fits.
 */
function placeholderCatalogue(entityKey: string): CombatAnimationCatalogue {
  const clip = (name: CombatAnimationName): AtlasClip => {
    const looping = (LOOPING_NAMES as readonly CombatAnimationName[]).includes(name)

    return {
      key: combatAnimationKey(entityKey, name),
      sheetKey: PLACEHOLDER_SHEET_KEY,
      sheetUrl: PLACEHOLDER_SHEET_URL,
      atlasUrl: PLACEHOLDER_ATLAS_URL,
      framePrefix: PLACEHOLDER_FRAME_PREFIX,
      frameSuffix: PLACEHOLDER_FRAME_SUFFIX,
      zeroPad: PLACEHOLDER_ZERO_PAD,
      firstFrame: 0,
      lastFrame: PLACEHOLDER_FRAME_COUNT - 1,
      frameRate: PLACEHOLDER_FRAME_RATE,
      sourceSize: { w: PLACEHOLDER_FRAME_WIDTH, h: PLACEHOLDER_FRAME_HEIGHT },
      repeat: looping ? -1 : 0,

      // Midpoint, and honest about being arbitrary: the placeholder has no
      // moment where anything connects. Spec D re-tunes every one of these
      // against real art, and §7.1 records that no test can flag a wrong value.
      ...(looping ? {} : { impactFrame: Math.floor(PLACEHOLDER_FRAME_COUNT / 2) }),
    }
  }

  // Written out key by key ON PURPOSE, with no cast.
  //
  // The version this replaces ended `Object.fromEntries(entries) as
  // CombatAnimationSet`, which asserted that all of `CombatAnimationName` was
  // present while three names were not — so `set.hit` type-checked and was
  // `undefined` at runtime (§2.2). Here the compiler checks the record: add a
  // name to `CombatAnimationName` and this object stops compiling until it has
  // a clip.
  return {
    idle: clip('idle'),
    ready: clip('ready'),
    standby: clip('standby'),
    cast: clip('cast'),
    death: clip('death'),
  }
}

// ---------------------------------------------------------------------------
// Static entities
// ---------------------------------------------------------------------------

/**
 * Peak bob, in SCREEN pixels. Small on purpose: this reads as breathing, not as
 * hovering. Not scaled by projection depth — see `IdleMotion.amplitudePx`.
 */
export const ENEMY_IDLE_AMPLITUDE_PX = 6

/** Base cycle. The jitter below spreads entities around it. */
const ENEMY_IDLE_BASE_PERIOD_MS = 2200

/** How far an entity's period may stray from the base, in ms, either way. */
const ENEMY_IDLE_PERIOD_JITTER_MS = 600

/**
 * Deterministic per-key jitter.
 *
 * Random would do the job on screen and be untestable; this is data, derived
 * from the key, so a test can assert that two different enemies do NOT share a
 * period. Without it a row of five wolves breathes as one organism, which reads
 * worse than not breathing at all.
 */
function idleMotionFor(entityKey: string): IdleMotion {
  let hash = 0

  for (let index = 0; index < entityKey.length; index++) {
    hash = (hash * 31 + entityKey.charCodeAt(index)) % 100000
  }

  const spread = (hash / 100000) * 2 - 1

  return {
    amplitudePx: ENEMY_IDLE_AMPLITUDE_PX,
    periodMs: Math.round(ENEMY_IDLE_BASE_PERIOD_MS + spread * ENEMY_IDLE_PERIOD_JITTER_MS),
  }
}

// ---------------------------------------------------------------------------
// The catalogue
// ---------------------------------------------------------------------------

/**
 * Fallback player entity key — same PNG as the mortal profile, different key.
 * Used when `combat-grid-view.ts` does not find the current profile's texture
 * loaded yet.
 *
 * Declared HERE rather than imported from `CombatPreload`: that module imports
 * this one, and the reverse edge would be a cycle.
 */
export const FALLBACK_PLAYER_ENTITY_KEY = 'player-mortal'

/**
 * Enemy template ids whose art is drawn. Resolved through
 * `resolveEnemyTextureKey` so the texture keys come from `EnemyArt`'s own table
 * rather than being spelled a second time here.
 */
const STATIC_ENEMY_TEMPLATE_IDS = [
  'mortal_ferocious_wild_boar',
  'mortal_ferocious_water_wolf',
  'mortal_ferocious_savage_tiger',
  'mortal_ferocious_mountain_bandit',
  'mortal_ferocious_giant_crocodile',
  'mortal_ferocious_stone_lynx',
  'mortal_ferocious_silver_fox',
  'mortal_ferocious_iron_boar',
  'mortal_ferocious_mud_ox',
  'mortal_ferocious_feral_dog',
  'mortal_wild_boar',
  'mortal_water_wolf',
  'mortal_savage_tiger',
  'mortal_mountain_bandit',
  'mortal_giant_crocodile',
  'mortal_stone_lynx',
  'mortal_silver_fox',
  'mortal_iron_boar',
  'mortal_mud_ox',
  'mortal_feral_dog',
] as const

function buildCatalogue(): Map<string, CombatEntityPresentation> {
  const entries = new Map<string, CombatEntityPresentation>()

  // The player animates (§3.2). Every profile, plus the fallback key.
  for (const profile of Object.values(PLAYER_VISUAL_PROFILES)) {
    entries.set(profile.combatTextureKey, {
      kind: 'animated',
      clips: placeholderCatalogue(profile.combatTextureKey),
    })
  }

  entries.set(FALLBACK_PLAYER_ENTITY_KEY, {
    kind: 'animated',
    clips: placeholderCatalogue(FALLBACK_PLAYER_ENTITY_KEY),
  })

  // Enemies are still images plus a bob (§3.2). Promoting one is a data change:
  // swap its entry for `{ kind: 'animated', clips: placeholderCatalogue(key) }`
  // and no playback code moves.
  for (const templateId of STATIC_ENEMY_TEMPLATE_IDS) {
    const textureKey = resolveEnemyTextureKey(templateId)

    if (!textureKey) {
      continue
    }

    entries.set(textureKey, {
      kind: 'static',
      texture: {
        textureKey,
        textureUrl: enemyTextureUrl(textureKey),
        sourceSize: { ...ENEMY_SOURCE_SIZE },
      },
      idleMotion: idleMotionFor(textureKey),
    })
  }

  return entries
}

const CATALOGUE = buildCatalogue()

/** Every entity key the catalogue knows. For the guards, and for preload. */
export function combatPresentationEntityKeys(): readonly string[] {
  return [...CATALOGUE.keys()]
}

/**
 * One function, one answer per entity.
 *
 * `undefined` for an entity with no drawn art at all — a realm whose enemies are
 * not in the Mortal batch, or a test fixture. Callers keep their existing
 * Rectangle fallback; this does NOT invent a presentation to avoid returning
 * nothing, because a silent downgrade is exactly what §3.2.1 refuses.
 */
export function presentationFor(entityKey: string): CombatEntityPresentation | undefined {
  return CATALOGUE.get(entityKey)
}

/** Every animated entity's clips, for preload and animation registration. */
export function animatedCombatEntities(): Array<{
  entityKey: string
  clips: CombatAnimationCatalogue
}> {
  const animated: Array<{ entityKey: string; clips: CombatAnimationCatalogue }> = []

  for (const [entityKey, presentation] of CATALOGUE) {
    if (presentation.kind === 'animated') {
      animated.push({ entityKey, clips: presentation.clips })
    }
  }

  return animated
}
