<script setup lang="ts">
import { useI18n } from 'vue-i18n'
import type { VictoryRewardDisplay } from './victoryUi'
defineProps<{ rewards: readonly VictoryRewardDisplay[] }>()
const { t } = useI18n()
</script>
<template><section class="victory-rewards" :aria-label="t('rewards')"><h2><span>{{ t('rewards') }}</span></h2><ul><li v-for="reward in rewards" :key="reward.id" :style="{ '--reward-tone': reward.tone }"><span class="reward-tile"><img v-if="reward.icon" :src="reward.icon" alt=""><i v-else-if="reward.motif==='jade'" class="jade-stone" aria-hidden="true" /><strong>{{ reward.amount }}</strong></span><span class="reward-name" :title="reward.name">{{ reward.name }}</span></li></ul><p v-if="!rewards.length" class="empty-rewards">{{ t('emptyRewards') }}</p></section></template>
<style scoped>
.victory-rewards h2 { display:flex; align-items:center; justify-content:center; gap:14px; margin:0 0 18px; font-size:17px; color:#fae6b4; font-weight:500; }.victory-rewards h2::before,.victory-rewards h2::after { content:''; width:105px; height:1px; background:linear-gradient(90deg,transparent,#907039); }.victory-rewards h2::after { transform:rotate(180deg); }.victory-rewards h2 span { padding:5px 24px; border:1px solid #a18248; background:linear-gradient(#293a29,#132018); clip-path:polygon(12px 0,calc(100% - 12px) 0,100% 50%,calc(100% - 12px) 100%,12px 100%,0 50%); }
.victory-rewards ul { display:flex; justify-content:center; gap:22px; overflow:auto; margin:0; padding:3px 5px 9px; scrollbar-width:thin; scrollbar-color:#ae8c47 transparent; }.victory-rewards li { display:flex; flex-direction:column; align-items:center; gap:8px; flex:none; width:110px; list-style:none; }.reward-tile { position:relative; display:grid; place-items:center; width:82px; height:82px; padding:10px; border:1px solid #cbb477; background:radial-gradient(ellipse at 50% 70%,color-mix(in srgb,var(--reward-tone) 22%,#152118),#09130e); box-shadow:inset 0 0 0 3px #4c3a19,inset 0 0 0 4px #a7834555,0 3px 6px #35220d44; border-radius:3px; }.reward-tile::after { content:''; position:absolute; inset:6px; border:1px solid var(--reward-tone); opacity:.6; pointer-events:none; }.reward-tile img { width:100%; height:100%; object-fit:contain; filter:drop-shadow(0 2px 3px #000); }.reward-tile strong { position:absolute; z-index:1; bottom:3px; right:5px; padding:1px 4px; background:#07150ce6; color:#f7e6b5; font-size:13px; text-shadow:0 1px 2px #000; }.reward-name { width:110px; overflow:hidden; text-overflow:ellipsis; white-space:nowrap; text-align:center; font-size:13px; color:#423014; font-weight:600; }.jade-stone { width:37px; height:47px; border:2px solid #acf8d3; transform:rotate(24deg); border-radius:45%; background:radial-gradient(ellipse at 35% 25%,#e0ffef,#41d9a7 30%,#0c6f51 60%,#03432a); box-shadow:inset 2px 0 5px #fff8,inset -4px -4px 9px #002c22,0 0 15px #64e9b066; }.empty-rewards { text-align:center; color:#6e5937; font-size:14px; }
.victory-rewards h2 { margin-bottom:10px; font-size:15px; }.victory-rewards h2 span { padding:3px 24px; }.reward-tile { width:74px; height:74px; }.victory-rewards li { gap:6px; }.victory-rewards ul { padding-bottom:5px; }.reward-name { font-size:12px; line-height:18px; }
</style>
