// ProductionCatalog (plan sec3/sec5/sec6) - Dia Gioi Thanh Van duy nhat trong
// scope hien tai (sec3.1): Pham Nhan/Luyen Khi/Truc Co, dung mot Lam,
// mot Quang, mot Dong Thien. Contract dung catalog de mo rong Dia Gioi
// sau nay ma khong sua engine. Validator tu choi Dia Gioi thieu nguon,
// trung loai hoac sai so realm.

import { getRealmIndex } from '../realm/realmSystem'
import type {
  ForestRewardDefinition,
  GrottoHerbDefinition,
  MineRewardDefinition,
  ProductionSiteDefinition,
  TerritoryDefinition,
} from './ProductionTypes'
import { HERB_AGES, PRODUCTION_SITE_KINDS } from './ProductionTypes'
import { HERB_AGE_WEIGHTS, MATERIAL_AGE_WEIGHTS } from './ProductionBalance'
import { REALM_TIERS } from '../realm/RealmTierMap'
import { isPillFamilyRecipeLiveAtRealm, PILL_FAMILIES } from '@/data/pill/PillFamilies'
import {
  buildProfessionMaterialId,
  herbBaseId,
  herbMaterialId,
} from '../profession/ProfessionMaterial'

export const TERRITORY_THANH_VAN: TerritoryDefinition = {
  id: 'thanh_van',
  name: 'Địa Giới Thanh Vân',
  realmIds: ['mortal', 'qi_refining', 'foundation_establishment'],
  productionSiteIds: {
    forest: 'thanh_van_lam',
    mine: 'thanh_van_quang',
    grotto: 'thanh_van_dong_thien',
  },
}

// =========================
// Ba nguon san xuat cua Thanh Van - level rieng, giu level khi dot pha
// (sec3.2). Upgrade cost bang Go cung realm + Linh Thach (sink chinh cua
// Lam sec5.2).
// =========================

const SITE_UPGRADE_COSTS = (): ProductionSiteDefinition['upgradeCosts'] => {
  // Thang tuoi theo tier - KHOP 1:1 voi AGE_BY_TIER cua
  // data/building/buildings.ts (tier 2=decade, 3-4=century,
  // 5-6=millennium, 7-8=myriad_year, 9=thuong_co).
  const ageByTier: Record<number, (typeof HERB_AGES)[number]> = {
    2: 'decade',
    3: 'century',
    4: 'century',
    5: 'millennium',
    6: 'millennium',
    7: 'myriad_year',
    8: 'myriad_year',
    9: 'thuong_co',
  }
  return REALM_TIERS.slice(1).map((realmId, index) => {
    const targetTier = index + 2
    return {
      woodMaterialId: buildProfessionMaterialId('wood', realmId, ageByTier[targetTier] ?? 'decade'),
      woodAmount: Math.round(5 * Math.pow(1.65, index)),
      spiritStone: Math.round(100 * Math.pow(2.2, index)),
    }
  })
}

function forestSite(): ProductionSiteDefinition {
  return {
    siteId: TERRITORY_THANH_VAN.productionSiteIds.forest,
    territoryId: TERRITORY_THANH_VAN.id,
    kind: 'forest',
    name: 'Thanh Vân Lâm',
    description: 'Rừng linh mộc của Địa Giới Thanh Vân — gỗ xây công trình và làm nhiên liệu đan lò.',
    maxLevel: 9,
    upgradeCosts: SITE_UPGRADE_COSTS(),
  }
}

function mineSite(): ProductionSiteDefinition {
  return {
    siteId: TERRITORY_THANH_VAN.productionSiteIds.mine,
    territoryId: TERRITORY_THANH_VAN.id,
    kind: 'mine',
    name: 'Huyền Thiết Quảng',
    description: 'Mạch quáng sâu của Thanh Vân — linh thạch quáng đi thẳng vào Khí Đường.',
    maxLevel: 9,
    upgradeCosts: SITE_UPGRADE_COSTS(),
  }
}

function grottoSite(): ProductionSiteDefinition {
  return {
    siteId: TERRITORY_THANH_VAN.productionSiteIds.grotto,
    territoryId: TERRITORY_THANH_VAN.id,
    kind: 'grotto',
    name: 'Thanh Vân Động Thiên',
    description: 'Động thiên kỳ trân dị thảo — mỗi đan phương có đúng một linh thảo riêng.',
    maxLevel: 9,
    upgradeCosts: SITE_UPGRADE_COSTS(),
  }
}

export const THANH_VAN_PRODUCTION_SITES: readonly ProductionSiteDefinition[] = [
  forestSite(),
  mineSite(),
  grottoSite(),
]

// =========================
// Reward catalogs (sec5.2/sec5.3/sec6.1)
// =========================

/** Lam: dung mot loai go theo realm x 5 tuoi (sec5.2 + gp123 6E C2). */
export const THANH_VAN_FOREST_REWARDS: readonly ForestRewardDefinition[] = TERRITORY_THANH_VAN.realmIds.flatMap(
  (realmId) =>
    HERB_AGES.map((age) => ({
      materialId: buildProfessionMaterialId('wood', realmId, age),
      realmId,
      age,
      // So luong theo tuoi nam o balance; definition giu 0 de resolver
      // tra MATERIAL_AGE_AMOUNTS - tranh lech hai nguon su that.
      amount: 0,
    })),
)

/** Quang: ba realm tier x nam tuoi (sec5.3 + gp123 6E C2). */
export const THANH_VAN_MINE_REWARDS: readonly MineRewardDefinition[] = HERB_AGES.flatMap(
  (age) =>
    TERRITORY_THANH_VAN.realmIds.map((realmId) => ({
      materialId: buildProfessionMaterialId('ore', realmId, age),
      realmId,
      age,
      // So luong theo tuoi nam o balance; definition giu 0 de resolver
      // tra MATERIAL_AGE_AMOUNTS - tranh lech hai nguon su that.
      amount: 0,
    })),
)

/**
 * Dong Thien: every non-retired pill family owns EXACTLY ONE primary
 * herb (section 6.1) - currently 7 live families x 5 age variants per
 * realm tier (QI-D8 prune in BASES below). The herb pool follows the
 * recipe's realm; each cycle rolls tier -> herb in tier -> age.
 *
 * Herb base identity is declared HERE (Phase 0 locked mapping, section
 * 13.3);
 * the full material id `${base}_${age}` is generated by data/materials.
 */
export interface GrottoHerbBase {
  baseId: string

  name: string

  /** Dan phuong (alchemy recipe id) duy nhat nuoi boi thao nay. */
  pillRecipeId: string

  realmId: string
}

// QI-D8 - retired families (Hoi Xuan Dan) are deferred: identity data
// stays resolvable, but the live Dong Thien pool stops generating their
// herbs while no real effect/sink exists.
// economy-review 2026-10-04: filter by the shared per-realm recipe
// predicate (isPillFamilyRecipeLiveAtRealm) so realm-retired recipes
// (hoi_linh_dan at mortal) stop minting orphan herbs too - before this
// the pool only honored family-level retirement and kept dropping a
// herb whose sole recipe could no longer be crafted or sold.
export const THANH_VAN_GROTTO_HERB_BASES: readonly GrottoHerbBase[] =
  TERRITORY_THANH_VAN.realmIds.flatMap((realmId) =>
    PILL_FAMILIES.filter((family) => isPillFamilyRecipeLiveAtRealm(family, realmId)).map((family) => ({
      baseId: herbBaseId(family.herbId, realmId),
      name: family.herbName,
      pillRecipeId: `alchemy_${family.id}_${realmId}`,
      realmId,
    })),
  )

export const THANH_VAN_GROTTO_HERBS: readonly GrottoHerbDefinition[] =
  THANH_VAN_GROTTO_HERB_BASES.flatMap((base) =>
    HERB_AGES.map((age) => ({
      materialId: herbMaterialId(base.baseId, age),
      realmId: base.realmId,
      pillRecipeId: base.pillRecipeId,
      age,
    })),
  )

// =========================
// Validator (sec3.1): tu choi Dia Gioi thieu nguon/trung loai/sai realm.
// =========================

export interface TerritoryValidationResult {
  valid: boolean

  errors: string[]
}

export function validateTerritory(
  territory: TerritoryDefinition,
  sites: readonly ProductionSiteDefinition[],
  forestRewards: readonly ForestRewardDefinition[],
  mineRewards: readonly MineRewardDefinition[],
  grottoHerbs: readonly GrottoHerbDefinition[],
): TerritoryValidationResult {
  const errors: string[] = []

  if (territory.realmIds.length !== 3) {
    errors.push(`Territory ${territory.id}: phải có đúng 3 cảnh giới`)
  }

  if (new Set(territory.realmIds).size !== territory.realmIds.length) {
    errors.push(`Territory ${territory.id}: cảnh giới trùng lặp`)
  }

  const territorySites = sites.filter((site) => site.territoryId === territory.id)

  for (const kind of PRODUCTION_SITE_KINDS) {
    const count = territorySites.filter((site) => site.kind === kind).length

    if (count !== 1) {
      errors.push(`Territory ${territory.id}: cần đúng 1 nguồn "${kind}", thấy ${count}`)
    }
  }

  const expectedSiteIds = new Set(Object.values(territory.productionSiteIds))

  for (const site of territorySites) {
    if (!expectedSiteIds.has(site.siteId)) {
      errors.push(`Territory ${territory.id}: site lạ ${site.siteId}`)
    }

    if (site.maxLevel < 1) {
      errors.push(`Site ${site.siteId}: maxLevel phải ≥ 1`)
    }
  }

  // Rewards phai phu du 3 realm tier cua Dia Gioi.
  for (const realmId of territory.realmIds) {
    if (!forestRewards.some((reward) => reward.realmId === realmId)) {
      errors.push(`Lâm ${territory.id}: thiếu gỗ cho tier ${realmId}`)
    }

    if (!mineRewards.some((reward) => reward.realmId === realmId)) {
      errors.push(`Quáng ${territory.id}: thiếu quáng cho tier ${realmId}`)
    }

    if (!grottoHerbs.some((herb) => herb.realmId === realmId)) {
      errors.push(`Động Thiên ${territory.id}: thiếu thảo cho tier ${realmId}`)
    }
  }

  // Realm cua reward phai thuoc Dia Gioi.
  for (const reward of [...forestRewards, ...mineRewards, ...grottoHerbs]) {
    if (!territory.realmIds.includes(reward.realmId)) {
      errors.push(`${territory.id}: reward ${reward.materialId} ngoài phạm vi Địa Giới`)
    }
  }

  return { valid: errors.length === 0, errors }
}

/** Kiem tra bat bien trong so giam dan (sec5.3/sec6.2) - goi o data integrity test. */
export function validateWeightOrdering(): string[] {
  const errors: string[] = []

  for (let index = 1; index < HERB_AGES.length; index++) {
    const previous = MATERIAL_AGE_WEIGHTS[HERB_AGES[index - 1]!]

    const current = MATERIAL_AGE_WEIGHTS[HERB_AGES[index]!]

    if (current >= previous) {
      errors.push(`Tuổi Gỗ/Khoáng ${HERB_AGES[index]} phải có trọng số thấp hơn ${HERB_AGES[index - 1]}`)
    }
  }

  for (let index = 1; index < HERB_AGES.length; index++) {
    const previous = HERB_AGE_WEIGHTS[HERB_AGES[index - 1]!]

    const current = HERB_AGE_WEIGHTS[HERB_AGES[index]!]

    if (current >= previous) {
      errors.push(`Niên đại ${HERB_AGES[index]} phải có trọng số thấp hơn ${HERB_AGES[index - 1]}`)
    }
  }

  return errors
}

/** Guard realm index dung chung - tranh import vong tu realmSystem o vai noi. */
export function realmSortKey(realmId: string): number {
  try {
    return getRealmIndex(realmId)
  } catch {
    return Number.MAX_SAFE_INTEGER
  }
}

/**
 * Mission D (spec D2) - realm -> territory-tier resolution at the
 * production boundary. A player realm ABOVE the territory's top
 * supported tier clamps DOWN to it (beta scope ends at
 * foundation_establishment; audit T3-17 - higher realms otherwise ran
 * on unsupported timing with a silent low-profile reward fallback, and
 * the manual start path rejected them outright). A realm absent from
 * the global realm order resolves to the BOTTOM tier: produce
 * something rather than silently stall.
 *
 * Extension point: post-beta territories declare their own realmIds;
 * this resolver clamps per-territory - no engine change needed.
 */
export function resolveTerritoryTier(territory: TerritoryDefinition, realmId: string): string {
  if (territory.realmIds.includes(realmId)) {
    return realmId
  }

  const realmIndex = getRealmIndex(realmId)

  if (realmIndex < 0) {
    return territory.realmIds[0]!
  }

  const supported = territory.realmIds.filter((id) => getRealmIndex(id) <= realmIndex)

  return supported[supported.length - 1] ?? territory.realmIds[0]!
}
