<script setup lang="ts">
import {useI18n} from 'vue-i18n'
import {resolveAssetUrl} from '@/presentation/assets/AssetBaseUrl'
import VictoryFidelityRewards from '@/components/scenes/victory/fidelity/VictoryFidelityRewards.vue'
import type {VictoryRewardDisplay} from '@/components/scenes/victory/fidelity/victoryUi'
import '@/assets/tien-hiep-outcomes.css'
defineProps<{stage:string;reason:string;rewards:readonly VictoryRewardDisplay[];notice:string}>()
const emit=defineEmits<{retry:[];home:[]}>()
const {t}=useI18n()
const paper=resolveAssetUrl('/assets/ui/tien-hiep-2026-10/runtime/panel-frame-v2.png')
const title=resolveAssetUrl('/assets/ui/tien-hiep-2026-10/runtime/ceremony-ribbon-red.png')
</script>
<template><section class="defeat-scene" :aria-label="t('defeat.title')"><div class="shade"/><header><h1><img :src="title" alt="" aria-hidden="true"><span>{{t('defeat.title')}}</span></h1><p class="stage">{{stage}}</p><p class="caption">{{t('defeat.caption')}}</p></header><div class="result-paper" :style="{borderImageSource:`url('${paper}')`}"><article class="reason"><span class="seal" aria-hidden="true">!</span><h2>{{t('defeat.reason')}}</h2><p>{{reason}}</p></article><VictoryFidelityRewards :rewards="rewards"/></div><div class="actions"><button class="retry" @click="emit('retry')">{{t('defeat.retry')}}</button><button class="home" @click="emit('home')">{{t('defeat.home')}}</button></div><p class="notice" role="status">{{notice}}</p><p class="preview">{{t('preview')}}</p></section></template>
<style scoped>
.defeat-scene{position:absolute;inset:0;font-family:var(--font-display,Georgia,serif);color:#f2dbab}.shade{position:absolute;inset:0;background:#0d1218d4}header{position:absolute;left:350px;top:106px;width:740px;text-align:center}h1{margin:0 auto;width:665px;height:208px}h1 img{width:100%;height:100%;object-fit:contain;filter:drop-shadow(0 4px 8px #0008)}.stage{margin:9px auto 0;width:max-content;max-width:650px;padding:7px 34px;border:1px solid #b4965a;background:linear-gradient(#3e2921,#261b19);font-size:20px}.caption{font-size:14px;margin:10px 0}.result-paper{position:absolute;left:255px;top:391px;width:930px;height:274px;padding:37px 59px;border:0 solid transparent;border-image-slice:300 fill;border-image-width:53px;display:grid;grid-template-columns:330px 1fr;gap:35px;filter:drop-shadow(0 9px 14px #0009)}.reason{position:relative;padding:0 15px 0 0;border-right:1px solid #98754766;color:#50311e}.reason h2{font-size:21px;margin:0 0 14px;padding-left:51px;line-height:38px}.reason p{font-size:15px;line-height:1.8;margin:0}.seal{position:absolute;top:0;left:0;width:38px;height:38px;border:2px solid #963d2c;color:#963d2c;font:bold 28px Georgia,serif;text-align:center;border-radius:50%}.result-paper :deep(.victory-rewards){padding-top:8px}.actions{position:absolute;left:454px;top:694px;display:flex;gap:30px}.actions button{width:251px;height:50px;border:1px solid #d3b773;border-radius:5px;box-shadow:inset 0 0 0 3px #efcf8533,0 3px 9px #0006;font:700 20px var(--font-display,Georgia,serif);cursor:pointer}.retry{color:#ffe0b0;background:linear-gradient(#753c2e,#351f1c)}.home{color:#38250e;background:linear-gradient(#ffe5a1,#c69649)}button:hover{filter:brightness(1.15)}button:focus-visible{outline:2px solid #ffe6a7;outline-offset:4px}.notice{position:absolute;top:750px;left:370px;width:700px;height:25px;margin:0;text-align:center;font-size:12px}.preview{position:absolute;bottom:13px;left:370px;width:700px;margin:0;text-align:center;font-size:10px;color:#bbaa92}
.defeat-scene :deep(*){box-sizing:border-box}
</style>
