import {test,expect} from './fixtures'
test('alchemy preview connects materials and switches existing pill art without gameplay mutation',async({page})=>{
 await page.setViewportSize({width:1672,height:941})
 await page.goto('/ui-landscape-design.html?example=home')
 const before=await page.evaluate(()=>JSON.stringify({...localStorage}))
 await page.locator('button[aria-label="alchemy"]').click()
 const panel=page.getByTestId('home-alchemy-panel')
 await expect(panel).toBeVisible()
 await expect(panel.locator('.alchemy-ingredient')).toHaveCount(4)
 await expect(panel.locator('.alchemy-connector')).toHaveCount(4)
 await expect(panel.locator('.alchemy-progress-row')).toHaveCount(4)
 await panel.locator('img').evaluateAll(es=>Promise.all(es.map(e=>(e as HTMLImageElement).decode())))
 await panel.locator('.alchemy-recipes button').nth(1).click()
 await expect(panel.locator('.alchemy-pill-art')).toHaveAttribute('src',/hoi_linh_dan/)
 await page.getByTestId('alchemy-start').click()
 await expect(panel.locator('.alchemy-progress-row').first()).toContainText('72%')
 await expect(panel.locator('.alchemy-connector i')).toHaveCount(4)
 const card=await panel.locator('.alchemy-progress-card').boundingBox()
 const btn=await page.getByTestId('alchemy-start').boundingBox()
 expect(btn!.y+btn!.height).toBeLessThanOrEqual(card!.y+card!.height)
 await page.screenshot({path:'docs/design/tien-hiep-ui-redesign-2026-10-05/runtime-evidence/alchemy-preview-v1.png'})
 await page.emulateMedia({reducedMotion:'reduce'})
 expect(await panel.locator('.alchemy-connector i').first().evaluate(e=>getComputedStyle(e).animationName)).toBe('none')
 expect(await page.evaluate(()=>JSON.stringify({...localStorage}))).toBe(before)
})
