import { test, expect } from './fixtures'
test('body art preview shares the silhouette and keeps progression presentation-only', async ({page}) => {
 const errors: string[]=[]
 page.on('pageerror',e=>errors.push(e.message))
 await page.setViewportSize({width:1672,height:941})
 await page.goto('/ui-landscape-design.html?example=home')
 const before=await page.evaluate(()=>JSON.stringify({...localStorage}))
 await page.locator('button[aria-label="body"]').click()
 const panel=page.getByTestId('home-body-panel')
 await expect(panel).toBeVisible()
 await expect(panel.locator('.body-family button')).toHaveCount(3)
 await expect(page.getByTestId('body-vertebra')).toHaveCount(10)
 await expect(page.getByTestId('body-forehead-node')).toHaveCount(3)
 await expect(panel.locator('.body-heart')).toHaveCount(1)
 await expect(panel.locator('.body-skin-layer')).toHaveAttribute('data-tier','1')
 await page.getByTestId('body-upgrade').click()
 await expect(panel.locator('.body-skin-layer')).toHaveAttribute('data-tier','0')
 await page.getByTestId('body-tab-khai').click()
 await expect(page.getByTestId('body-meridian-node')).toHaveCount(10)
 await page.getByRole('button',{name:'Trang sau',exact:true}).click()
 await expect(panel.locator('.body-pagination span')).toHaveText('2 / 8')
 for(const tab of ['ren','khai','dan']){
  await page.getByTestId('body-tab-'+tab).click()
  await panel.locator('img').evaluateAll(es=>Promise.all(es.map(e=>(e as HTMLImageElement).decode())))
  const card=await panel.locator('.body-stat-card').boundingBox()
  const button=await page.getByTestId('body-upgrade').boundingBox()
  expect(button!.y+button!.height).toBeLessThanOrEqual(card!.y+card!.height)
  expect(await panel.locator('img').evaluateAll(es=>es.every(e=>(e as HTMLImageElement).naturalWidth>0))).toBe(true)
 }
 await expect(panel.locator('.body-galaxy-piece')).toHaveCount(6)
 await page.screenshot({path:'docs/design/tien-hiep-ui-redesign-2026-10-05/runtime-evidence/body-grand-cycle-v1.png'})
 await page.getByTestId('body-tab-ren').click()
 await page.screenshot({path:'docs/design/tien-hiep-ui-redesign-2026-10-05/runtime-evidence/body-combined-silver-v1.png'})
 await page.getByTestId('body-upgrade').click()
 await page.screenshot({path:'docs/design/tien-hiep-ui-redesign-2026-10-05/runtime-evidence/body-combined-gold-v1.png'})
 await page.getByTestId('body-tab-dan').click()
 await page.emulateMedia({reducedMotion:'reduce'})
 expect(await panel.locator('.orbiting').first().evaluate(e=>getComputedStyle(e).animationName)).toBe('none')
 expect(await page.evaluate(()=>JSON.stringify({...localStorage}))).toBe(before)
 expect(errors).toEqual([])
})
