import {test,expect} from './fixtures'
test('formation layout uses local placement draft and removes redundant forge navigation',async({page})=>{
 await page.setViewportSize({width:1672,height:941})
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message))
 await page.goto('/ui-landscape-design.html?example=home')
 const before=await page.evaluate(()=>JSON.stringify({...localStorage}))
 await expect(page.locator('.home-independent-navigation button[aria-label="forge"]')).toHaveCount(0)
 await page.locator('button[aria-label="formation"]').click()
 const panel=page.getByTestId('home-formation-panel')
 await expect(panel).toBeVisible()
 await expect(panel.locator('.formation-grid button')).toHaveCount(9)
 await panel.locator('img').evaluateAll(es=>Promise.all(es.map(e=>(e as HTMLImageElement).decode())))
 await panel.locator('.formation-grid button').nth(1).click()
 await panel.locator('.formation-roster-items button').nth(4).click()
 await expect(panel.locator('.formation-grid button').nth(1).locator('.formation-person')).toHaveAttribute('src',/ziyuan/)
 await expect(panel.locator('.formation-grid button').nth(8)).toBeDisabled()
 await page.getByTestId('formation-confirm').click()
 await expect(panel.getByRole('status')).toContainText('chưa lưu')
 await page.screenshot({path:'docs/design/tien-hiep-ui-redesign-2026-10-05/runtime-evidence/formation-preview-v1.png'})
 await page.getByTestId('formation-tab-rank').click()
 await expect(panel).toContainText('Tiến Độ Tăng Bậc')
 expect(await page.evaluate(()=>JSON.stringify({...localStorage}))).toBe(before)
 expect(errors).toEqual([])
})
