import {test,expect} from './fixtures'
test('inventory concept reuses item art and unfinished navigation is locked last',async({page})=>{
 await page.setViewportSize({width:1672,height:941})
 await page.goto('/ui-landscape-design.html?example=home')
 const before=await page.evaluate(()=>JSON.stringify({...localStorage}))
 const nav=page.locator('.home-independent-navigation button')
 expect(await nav.evaluateAll(es=>es.slice(-5).map(e=>e.getAttribute('aria-label')))).toEqual(['artifact','companion','guild','sect','portal'])
 for(const id of ['artifact','companion','guild','sect','portal']) await expect(page.locator(`.home-independent-navigation button[aria-label="${id}"]`)).toBeDisabled()
 await page.locator('button[aria-label="inventory"]').click()
 const panel=page.getByTestId('home-inventory-panel')
 await expect(panel).toBeVisible()
 await expect(panel).toContainText('Trữ Vật')
 await page.getByTestId('inventory-tab-decompose').click()
 await expect(panel.locator('.inventory-grid .equipment-art-slot')).toHaveCount(48)
 await expect(panel.locator('.inventory-filters button')).toHaveCount(7)
 await panel.locator('img').evaluateAll(es=>Promise.all(es.map(e=>(e as HTMLImageElement).decode())))
 await panel.locator('.inventory-filters button').nth(1).click()
 await expect(panel.locator('.equipment-slot-item')).toHaveCount(3)
 await panel.locator('input').fill('không tồn tại')
 await expect(panel.locator('.equipment-slot-item')).toHaveCount(0)
 for(const id of ['materials','pills','decompose']){
 await page.getByTestId('inventory-tab-'+id).click()
 await panel.locator('img').evaluateAll(es=>Promise.all(es.map(e=>(e as HTMLImageElement).decode())))
 }
 await page.getByTestId('inventory-cell-0').click()
 await page.getByTestId('inventory-decompose').click()
 await expect(panel.getByRole('status')).toContainText('không tiêu hao')
 await page.screenshot({path:'docs/design/tien-hiep-ui-redesign-2026-10-05/runtime-evidence/inventory-concept-v1.png'})
 await page.locator('button[aria-label="equipment"]').click()
 await expect(page.getByTestId('equipment-dissolve')).toBeVisible()
 await page.getByTestId('equipment-dissolve').click()
 await expect(page.getByRole('status')).toContainText('Hóa Luyện')
 expect(await page.evaluate(()=>JSON.stringify({...localStorage}))).toBe(before)
})
