import { expect, test } from './fixtures'
import { assertNoBrowserErrors, bootToGuestHome, collectBrowserErrors, createCharacterThroughUi, enterHome } from './helpers'

const evidence = 'docs/design/tien-hiep-ui-redesign-2026-10-05/runtime-evidence'

test('admitted production and vendor overlays preserve building header and close', async ({ page }) => {
  test.setTimeout(120_000)
  const errors = collectBrowserErrors(page)
  await page.setViewportSize({ width: 1672, height: 941 })
  await bootToGuestHome(page)
  await createCharacterThroughUi(page, 'Thanh Vân Phường')
  await enterHome(page)
  await page.locator('[data-df-building="gathering_outpost"]').click()
  await expect(page.locator('.production-panel.pc-auxiliary')).toBeVisible()
  await expect(page.locator('.production-panel .site-card')).toHaveCount(3)
  await expect(page.locator('.overlay-panel:visible .building-heading__name')).toHaveCount(1)
  expect(await page.locator('.overlay-panel:visible .building-heading__upgrade-area').count()).toBeLessThanOrEqual(1)
  await expect(page.locator('.worker-allocation')).toHaveCount(0)
  const auto = page.locator('.site-card__auto input').first()
  await auto.uncheck()
  await expect(auto).not.toBeChecked()
  await auto.check()
  await expect(auto).toBeChecked()
  for (const [width,height] of [[1280,720],[1672,941]]) {
    await page.setViewportSize({ width: width!, height: height! })
    await page.screenshot({ path: `${evidence}/wire-production-${width}.png` })
    const card = await page.locator('.overlay-panel:visible .overlay-panel__card').boundingBox()
    expect(card!.x + card!.width).toBeLessThanOrEqual(width! + 1)
    expect(card!.y + card!.height).toBeLessThanOrEqual(height! + 1)
    await page.locator('.site-card__upgrade-button').first().scrollIntoViewIfNeeded()
    await expect(page.locator('.site-card__upgrade-button').first()).toBeVisible()
  }
  await page.keyboard.press('Escape')
  await expect(page.locator('.production-panel')).toHaveCount(0)
  await page.locator('[data-df-building="vendor"]').click()
  await expect(page.locator('.vendor-panel.pc-auxiliary')).toBeVisible()
  await expect(page.locator('.overlay-panel:visible .building-heading__name')).toHaveCount(1)
  expect(await page.locator('.overlay-panel:visible .building-heading__upgrade-area').count()).toBeLessThanOrEqual(1)
  await page.screenshot({ path: `${evidence}/wire-vendor-1672.png` })
  await page.keyboard.press('Escape')
  await expect(page.locator('.vendor-panel')).toHaveCount(0)
  assertNoBrowserErrors(errors)
})

test('release-hidden formation and owned companion authoring surfaces retain real content', async ({ page }) => {
  const errors = collectBrowserErrors(page)
  await page.setViewportSize({ width: 1672, height: 941 })
  await page.goto('/ui-secondary.html')
  await expect(page.locator('.tran-phap-panel.pc-auxiliary')).toBeVisible()
  await expect(page.locator('.tran-phap-panel__cell')).toHaveCount(9)
  await expect(page.locator('.tran-phap-panel__preview-canvas canvas')).toBeVisible()
  await page.locator('.tran-phap-panel__formation-button').first().click()
  await expect(page.locator('.tran-phap-panel__formation-button').first()).toHaveAttribute('aria-pressed', 'true')
  const projection = await page.locator('.tran-phap-panel__grid-stack').boundingBox()
  expect(projection!.width).toBeGreaterThan(300)
  expect(projection!.height).toBeGreaterThan(300)
  await page.locator('.tran-phap-panel__cell--enabled').first().evaluate((cell) => {
    const transfer = new DataTransfer()
    transfer.setData('text/plain', 'player')
    cell.dispatchEvent(new DragEvent('drop', { dataTransfer: transfer, bubbles: true }))
  })
  await expect(page.locator('.tran-phap-panel__cell--occupied')).toHaveCount(1)
  await page.locator('.tran-phap-panel__confirm').click()
  // The isolated fixture exposes the editor, while the production owner
  // still rejects release-hidden commits and resets the rejected draft.
  await expect(page.locator('.tran-phap-panel__cell--occupied')).toHaveCount(0)
  await page.locator('[data-preview-tab="companion"]').click()
  await page.locator('[data-preview-tab="tran_phap"]').click()
  await expect(page.locator('.tran-phap-panel__cell--occupied')).toHaveCount(0)
  await page.locator('.tran-phap-panel__formation-button').first().click()
  await page.waitForTimeout(600)
  await page.screenshot({ path: `${evidence}/wire-formation-authoring-1672.png` })
  await page.locator('[data-preview-tab="companion"]').click()
  await expect(page.locator('.companion-panel.pc-auxiliary')).toBeVisible()
  await page.locator('.companion-panel__card').first().click()
  await expect(page.locator('.companion-panel__feed-controls')).toBeVisible()
  await page.screenshot({ path: `${evidence}/wire-companion-authoring-1672.png` })
  for (const [id,selector] of [['chieu_mo','.chieu-mo'],['duyen_phan','.duyen-phan'],['qua_tang','.qua-tang']]) {
    await page.locator(`[data-preview-tab="${id}"]`).click()
    await expect(page.locator(`${selector}.pc-auxiliary`)).toBeVisible()
    await page.screenshot({ path: `${evidence}/wire-${id}-authoring-1672.png` })
  }
  await page.locator('[data-preview-tab="system"]').click()
  await page.locator('[data-preview-dialog="lore"]').click()
  await expect(page.locator('.lore-modal__panel.pc-auxiliary')).toBeVisible()
  await expect(page.locator('.lore-modal')).toHaveCSS('opacity', '1')
  await page.screenshot({ path: `${evidence}/wire-lore-authoring-1672.png` })
  await page.locator('.lore-modal__close').click()
  await expect(page.locator('.lore-modal')).toHaveCount(0)
  assertNoBrowserErrors(errors)
})
