import { expect, test } from './fixtures'
import { assertNoBrowserErrors, bootToGuestHome, collectBrowserErrors, createCharacterThroughUi, enterHome } from './helpers'

const evidence = 'docs/design/tien-hiep-ui-redesign-2026-10-05/runtime-evidence'

test('live settings retains save, audio, display and modal cancellation', async ({ page }) => {
  const errors = collectBrowserErrors(page)
  await page.setViewportSize({ width: 1672, height: 941 })
  await bootToGuestHome(page)
  await createCharacterThroughUi(page, 'Thanh Vân Kiểm')
  await enterHome(page)
  await page.locator('[data-df-navigation="settings"]').click()
  const settings = page.locator('.pc-settings-root')
  await expect(settings).toBeVisible()
  await page.getByTestId('settings-save-button').click()
  await expect(page.locator('.settings-panel__hint')).toBeVisible()
  await page.screenshot({ path: `${evidence}/wired-settings-save-1672.png` })
  await settings.getByRole('button', { name: 'Tải Lại' }).click()
  const confirm = page.locator('.confirm-modal__panel')
  await expect(confirm).toBeVisible()
  await expect(confirm.locator('.pc-paper-chrome')).toHaveCount(1)
  await page.screenshot({ path: `${evidence}/wired-confirm-1672.png` })
  await page.keyboard.press('Escape')
  await expect(confirm).toHaveCount(0)
  await expect(settings).toBeVisible()
  await settings.locator('[data-section="audio"]').click()
  await expect(page.getByTestId('settings-audio-toggle')).toBeVisible()
  await page.getByTestId('settings-audio-toggle').click()
  await expect(page.getByTestId('settings-audio-volume')).toBeDisabled()
  await page.getByTestId('settings-audio-toggle').click()
  await expect(page.getByTestId('settings-audio-volume')).toBeEnabled()
  await page.screenshot({ path: `${evidence}/wired-settings-audio-1672.png` })
  await settings.locator('[data-section="display"]').click()
  await expect(settings.locator('[data-hk-region="ui-scale"]')).toBeVisible()
  await page.screenshot({ path: `${evidence}/wired-settings-display-1672.png` })
  await settings.locator('[data-section="support"]').click()
  await settings.getByRole('button', { name: /Gửi.*Phản Hồi/i }).click()
  await expect(page.locator('.feedback-dialog')).toBeVisible()
  await expect(page.getByTestId('feedback-submit')).toBeInViewport()
  await page.screenshot({ path: `${evidence}/wired-feedback-1672.png` })
  await page.keyboard.press('Escape')
  await expect(page.locator('.feedback-dialog')).toHaveCount(0)
  await expect(settings).toBeVisible()
  for (const [width, height] of [[1280, 720], [1920, 1080]]) {
    await page.setViewportSize({ width: width!, height: height! })
    await page.screenshot({ path: `${evidence}/wired-settings-support-${width}.png` })
    const box = await settings.locator('.settings-panel__workspace').boundingBox()
    expect(box!.x + box!.width).toBeLessThanOrEqual(width! + 1)
    expect(box!.y + box!.height).toBeLessThanOrEqual(height! + 1)
  }
  await page.keyboard.press('Escape')
  await expect(settings).toHaveCount(0)
  assertNoBrowserErrors(errors)
})

test('Escape closes the page menu before closing its live page', async ({ page }) => {
  await bootToGuestHome(page)
  await createCharacterThroughUi(page, 'Thanh Vân Menu')
  await enterHome(page)
  await page.locator('[data-df-navigation="settings"]').click()
  const trigger = page.locator('.pc-paper-scene-actions > button').nth(1)
  await trigger.click()
  await expect(page.locator('.pc-paper-scene-actions__menu')).toBeVisible()
  await page.keyboard.press('Escape')
  await expect(page.locator('.pc-paper-scene-actions__menu')).toHaveCount(0)
  await expect(page.locator('.pc-settings-root')).toBeVisible()
  await expect(trigger).toBeFocused()
  await page.keyboard.press('Escape')
  await expect(page.locator('.pc-settings-root')).toHaveCount(0)
})
