import {test,expect} from './fixtures'
test('realm track slides and overlays next card without changing saved state',async({page})=>{
 await page.setViewportSize({width:1672,height:941})
 await page.goto('/ui-landscape-design.html?example=home')
 const before=await page.evaluate(()=>JSON.stringify({...localStorage}))
 await page.locator('button[aria-label="realm"]').click()
 const panel=page.getByTestId('home-realm-panel')
 await expect(panel).toBeVisible()
 await panel.locator('img').evaluateAll(es=>Promise.all(es.map(e=>(e as HTMLImageElement).decode())))
 await expect(page.getByTestId('realm-active-card')).toContainText('Tầng 12')
 const initial=await page.getByTestId('realm-track').getAttribute('style')
 await page.getByTestId('realm-upgrade').click()
 await expect(page.getByTestId('realm-active-card')).toContainText('Tầng 13')
 await expect(page.getByTestId('realm-upgrade')).toHaveAttribute('aria-disabled','false')
 expect(await page.getByTestId('realm-track').getAttribute('style')).not.toBe(initial)
 await page.screenshot({path:'docs/design/tien-hiep-ui-redesign-2026-10-05/runtime-evidence/realm-slide-preview-v1.png'})
 await page.emulateMedia({reducedMotion:'reduce'})
 await page.getByTestId('realm-upgrade').click()
 await expect(page.getByTestId('realm-active-card')).toContainText('Tầng 16')
 await expect(page.getByTestId('realm-upgrade')).toHaveAttribute('aria-disabled','false')
 await page.getByTestId('realm-tribulation').click()
 await expect(page.getByTestId('realm-active-card')).toContainText('Luyện Khí')
 await expect(page.getByTestId('realm-active-card')).toContainText('Tầng 1')
 await expect(page.getByTestId('realm-tribulation')).toHaveAttribute('aria-disabled','true')
 await page.getByTestId('realm-tribulation').dispatchEvent('click')
 await expect(page.getByTestId('realm-active-card')).toContainText('Tầng 1')
 expect(await page.evaluate(()=>JSON.stringify({...localStorage}))).toBe(before)
})
