import {test,expect} from './fixtures'
test('technique preview leaves manual art empty and does not persist mock progression',async({page})=>{
 await page.setViewportSize({width:1672,height:941})
 await page.goto('/ui-landscape-design.html?example=home')
 const before=await page.evaluate(()=>JSON.stringify({...localStorage}))
 await page.locator('button[aria-label="technique"]').click()
 const panel=page.getByTestId('home-technique-panel')
 await expect(panel).toBeVisible()
 await expect(page.getByTestId('technique-art-space')).toBeEmpty()
 await expect(panel.locator('.skill-art-node')).toHaveCount(4)
 await panel.locator('img').evaluateAll(es=>Promise.all(es.map(e=>(e as HTMLImageElement).decode())))
 await page.getByTestId('technique-upgrade').click()
 await expect(panel.locator('.mastery-label')).toContainText('300 / 300')
 expect(await page.evaluate(()=>JSON.stringify({...localStorage}))).toBe(before)
 const card=await panel.locator('.technique-stat-card').boundingBox()
 const button=await page.getByTestId('technique-upgrade').boundingBox()
 expect(button!.y+button!.height).toBeLessThanOrEqual(card!.y+card!.height)
 await page.screenshot({path:'docs/design/tien-hiep-ui-redesign-2026-10-05/runtime-evidence/technique-empty-art-v1.png'})
})
