<script setup lang="ts">
import { useI18n } from 'vue-i18n'
import type { QuestDisplay } from './questUi'
import type { VictoryRewardDisplay } from '@/components/scenes/victory/fidelity/victoryUi'
import VictoryFidelityRewards from '@/components/scenes/victory/fidelity/VictoryFidelityRewards.vue'
defineProps<{quest:QuestDisplay;rewards:readonly VictoryRewardDisplay[]}>()
const emit=defineEmits<{action:[id:string]}>()
const {t}=useI18n()
</script>
<template><article class="quest-detail"><header class="banner"><img :src="quest.image" alt=""><h2>{{quest.name}}</h2><span>{{t(`questPreview.${quest.status}`)}}</span></header><p class="description">{{quest.description}}</p><h3>{{t('questPreview.objectives')}}</h3><ul class="objectives"><li v-for="item in quest.objectives" :key="item.id" :class="{done:item.done}"><span aria-hidden="true">{{item.done?'✓':'◇'}}</span><span>{{item.label}}</span><b>{{item.value}}</b></li></ul><VictoryFidelityRewards :rewards="rewards"/><button class="action" @click="emit('action',quest.id)">{{t(quest.status==='ready'?'questPreview.claim':quest.status==='claimed'?'questPreview.claimed':'questPreview.follow')}}</button></article></template>
<style scoped>
.quest-detail{height:100%;display:flex;flex-direction:column;gap:11px;color:#403321}.banner{height:115px;position:relative;flex-shrink:0;overflow:hidden;border:1px solid #9b804c;box-shadow:0 3px 8px #45321c33}.banner img{width:100%;height:100%;object-fit:cover;object-position:50% 38%;filter:brightness(.65)}.banner h2{position:absolute;left:21px;bottom:13px;margin:0;font-size:26px;color:#ffe6aa;text-shadow:0 2px 4px #000}.banner>span{position:absolute;right:14px;top:12px;background:#172e23e6;padding:5px 12px;color:#ead9a9;border:1px solid #b79757;font-size:12px}.description{margin:0;font-size:14px;line-height:1.65}h3{margin:0;font-size:18px;color:#554026;border-bottom:1px solid #9d804a66;padding-bottom:6px}.objectives{padding:0;margin:0;list-style:none;font-size:14px}.objectives li{display:flex;gap:10px;align-items:center;height:29px}.objectives b{margin-left:auto}.done{color:#316e4c}.action{height:40px;min-height:40px;width:240px;align-self:center;border:1px solid #a08545;background:linear-gradient(#315542,#132c20);color:#f9dfa0;font:700 17px var(--font-display,Georgia,serif);cursor:pointer;box-shadow:inset 0 0 0 3px #ddbc6e33}.action:hover{filter:brightness(1.15)}.action:focus-visible{outline:2px solid #305d40;outline-offset:3px}.quest-detail :deep(.rewards-heading){font-size:16px}.quest-detail :deep(.reward-slot){width:58px;height:58px}.quest-detail :deep(.reward-name){font-size:11px}
.quest-detail{gap:6px}.banner{height:90px}.banner h2{font-size:23px}.description{font-size:13px;line-height:1.5}h3{font-size:16px;padding-bottom:4px}.objectives li{height:24px}.action{height:36px;min-height:36px}.quest-detail :deep(.victory-rewards h2){font-size:13px;margin-bottom:4px}.quest-detail :deep(.reward-tile){width:54px;height:54px;padding:7px}.quest-detail :deep(.victory-rewards li){width:85px;gap:3px}.quest-detail :deep(.reward-name){width:85px;font-size:11px}
</style>
