// BETA-FINAL PR12 / spec B6 - the shared update projection contract.
//
// One typed UpdateState flows main -> renderer over the allowlisted IPC
// surface; the renderer never receives a feed URL, a file path, a
// publisher blob or any updater primitive it could abuse - only this
// sanitized projection plus the four action channels (check / download /
// install-request / install-result). Both sides validate at the boundary:
// the renderer parses UpdateState before rendering, the main side parses
// the install result before installing.
//
// No Vue/Phaser/Node imports - this file must stay bundle-neutral.

import type { FlushResult } from '../session/FlushResult'

/** The phases of the one update state machine owned by the main-process
 *  UpdateService. 'unsupported' means this build carries no verified feed
 *  configuration (development builds, missing packaged manifest) - it is
 *  terminal for the lifetime of the process, not an error. */
export type UpdatePhase =
  | 'idle'
  | 'checking'
  | 'unavailable'
  | 'available'
  | 'downloading'
  | 'downloaded'
  | 'installing'
  | 'error'
  | 'unsupported'

export type UpdateErrorCode =
  | 'CHECK_FAILED'
  | 'DOWNLOAD_FAILED'
  | 'DOWNLOAD_CANCELLED'
  | 'CANDIDATE_CORRUPT'
  | 'MANIFEST_INVALID'
  | 'OLDER_VERSION'
  | 'WRONG_CHANNEL'
  | 'WRONG_ENVIRONMENT'
  | 'PUBLISHER_MISMATCH'
  | 'FEED_CONFIG_INVALID'
  | 'FLUSH_FAILED'
  | 'STALE_GENERATION'
  | 'INSTALL_TIMEOUT'
  | 'INSTALL_NOT_READY'
  | 'UNSUPPORTED'

export interface UpdateCandidate {
  /** Semver string from the verified feed manifest. */
  version: string
  /** Prerelease/channel tag proven to match this build's channel. */
  channel: string
  releaseName?: string
  releaseNotes?: string
  releaseDate?: string
}

export interface UpdateProgress {
  /** 0..100 - provider-reported, never computed renderer-side. */
  percent: number
  bytesPerSecond: number
  transferred: number
  total: number
}

export interface UpdateError {
  code: UpdateErrorCode
  message: string
  /** Retryable failures keep the downloaded/available candidate so an
   *  explicit user retry can resume; terminal ones cleared it. */
  retryable: boolean
}

export interface UpdateState {
  phase: UpdatePhase
  /** This running build (injected BuildIdentity values). */
  currentVersion: string
  currentBuildId: string
  /** Present whenever a verified candidate exists: 'available',
   *  'downloading', 'downloaded', 'installing' and retained across a
   *  retryable 'error'. Absent on 'unavailable'/'unsupported'/'idle'. */
  candidate?: UpdateCandidate
  /** Present only while 'downloading'. */
  progress?: UpdateProgress
  error?: UpdateError
}

/** The feed identity the packaged app-update.yml must declare verbatim.
 *  A mismatch means the packaged updater points somewhere we did not
 *  build - the service fails closed instead of following it. */
export interface UpdateFeedExpectation {
  provider: 'github' | 'generic'
  /** github provider fields; absent for generic. */
  owner?: string
  repo?: string
  /** generic provider: must be an https:// URL - http feed is rejected. */
  url?: string
  channel: string
  /** Expected code-signing publisher CN while EXT-02 is unresolved the
   *  packaged manifest may legitimately carry none; once pinned here a
   *  packaged publisherName must equal it exactly. */
  publisherName: string | null
}

/** The Beta feed contract: GitHub releases on this repository's own
 *  origin, 'beta' channel (beta.yml app-update manifest generated by
 *  electron-builder). The matching electron-builder.yml `publish:` block
 *  is asserted equal by scripts/release/update-feed.test.mjs - the two
 *  declarations cannot drift apart silently. */
export const EXPECTED_UPDATE_FEED: UpdateFeedExpectation = Object.freeze({
  provider: 'github',
  owner: 'hnkm080596-svg',
  repo: 'tutienidle',
  channel: 'beta',
  // EXT-02 (signing service) is still external: no real publisher CN can
  // be declared yet. While null, a packaged manifest that DOES declare a
  // publisherName is rejected - we never silently trust an unexpected
  // signer; the pin is filled in by the signing PR with the real CN.
  publisherName: null,
})

/** The wire shape of an install result - the SAME FlushResult contract
 *  the quit path consumes (B1-D): request/generation binding plus the
 *  committed remote revision on success. */
export type UpdateInstallResult = FlushResult

/** Main -> renderer: the install preparation request quoting the
 *  main-minted requestId the result must carry. */
export interface UpdateInstallRequest {
  requestId: string
}

/** Main -> renderer: the pending install failed (bad result or timeout);
 *  the user picks retry (a NEW requestId) or later. Never implicit. */
export interface UpdateInstallFailedNotice {
  requestId: string
  status: string
  code?: string
}

// ---------------------------------------------------------------------------
// Version comparison - semver precedence for x.y.z(-tag.n) versions only.
// The Beta line is prerelease-tagged (`0.1.0-beta.0`); an update must be
// STRICTLY newer, and a stable release outranks any prerelease of the same
// numeric triple per semver rules 9-11.
// ---------------------------------------------------------------------------

const VERSION_RE = /^(\d+)\.(\d+)\.(\d+)(?:-([0-9A-Za-z.-]+))?$/

export interface ParsedVersion {
  major: number
  minor: number
  patch: number
  /** Dot-separated prerelease identifiers, or null for a stable release. */
  prerelease: string[] | null
}

export function parseVersion(value: unknown): ParsedVersion | null {
  if (typeof value !== 'string') return null
  const match = VERSION_RE.exec(value)
  if (!match) return null
  const prerelease = match[4] !== undefined ? match[4].split('.') : null
  if (prerelease !== null && prerelease.some((id) => id === '')) return null
  return {
    major: Number(match[1]),
    minor: Number(match[2]),
    patch: Number(match[3]),
    prerelease,
  }
}

/** Semver precedence: negative = a < b, 0 = equal precedence, positive = a > b. */
export function compareVersions(a: ParsedVersion, b: ParsedVersion): number {
  if (a.major !== b.major) return a.major - b.major
  if (a.minor !== b.minor) return a.minor - b.minor
  if (a.patch !== b.patch) return a.patch - b.patch

  if (a.prerelease === null && b.prerelease === null) return 0
  // A stable release outranks any prerelease of the same triple.
  if (a.prerelease === null) return 1
  if (b.prerelease === null) return -1

  const len = Math.max(a.prerelease.length, b.prerelease.length)
  for (let i = 0; i < len; i += 1) {
    const ai = a.prerelease[i]
    const bi = b.prerelease[i]
    if (ai === undefined) return -1 // fewer identifiers = lower precedence
    if (bi === undefined) return 1
    if (ai === bi) continue
    const an = /^\d+$/.test(ai)
    const bn = /^\d+$/.test(bi)
    if (an && bn) return Number(ai) - Number(bi)
    if (an) return -1 // numeric identifiers sort below alphanumeric
    if (bn) return 1
    return ai < bi ? -1 : 1
  }
  return 0
}

/** The prerelease channel tag a candidate must carry for this build:
 *  beta builds only ever install `x.y.z-beta.n` candidates; development
 *  builds have no feed and no tag. */
export function expectedChannelTag(releaseChannel: 'development' | 'beta'): string | null {
  return releaseChannel === 'beta' ? 'beta' : null
}

// ---------------------------------------------------------------------------
// Boundary validation (main -> renderer UpdateState push / get-state reply)
// ---------------------------------------------------------------------------

const PHASES = new Set<UpdatePhase>([
  'idle',
  'checking',
  'unavailable',
  'available',
  'downloading',
  'downloaded',
  'installing',
  'error',
  'unsupported',
])

const ERROR_CODES = new Set<UpdateErrorCode>([
  'CHECK_FAILED',
  'DOWNLOAD_FAILED',
  'DOWNLOAD_CANCELLED',
  'CANDIDATE_CORRUPT',
  'MANIFEST_INVALID',
  'OLDER_VERSION',
  'WRONG_CHANNEL',
  'WRONG_ENVIRONMENT',
  'PUBLISHER_MISMATCH',
  'FEED_CONFIG_INVALID',
  'FLUSH_FAILED',
  'STALE_GENERATION',
  'INSTALL_TIMEOUT',
  'INSTALL_NOT_READY',
  'UNSUPPORTED',
])

const MAX_STATE_TEXT = 4_096

function readBoundedString(value: unknown, max = MAX_STATE_TEXT): string | undefined {
  return typeof value === 'string' && value.length > 0 && value.length <= max
    ? value
    : undefined
}

function isRecord(value: unknown): value is Record<string, unknown> {
  return value !== null && typeof value === 'object' && !Array.isArray(value)
}

function readCandidate(value: unknown): UpdateCandidate | undefined {
  if (!isRecord(value)) return undefined
  const version = readBoundedString(value.version, 64)
  const channel = readBoundedString(value.channel, 64)
  if (version === undefined || channel === undefined) return undefined
  const candidate: UpdateCandidate = { version, channel }
  const releaseName = readBoundedString(value.releaseName)
  const releaseNotes = readBoundedString(value.releaseNotes, 16_384)
  const releaseDate = readBoundedString(value.releaseDate, 64)
  if (releaseName !== undefined) candidate.releaseName = releaseName
  if (releaseNotes !== undefined) candidate.releaseNotes = releaseNotes
  if (releaseDate !== undefined) candidate.releaseDate = releaseDate
  return candidate
}

function readProgress(value: unknown): UpdateProgress | undefined {
  if (!isRecord(value)) return undefined
  const { percent, bytesPerSecond, transferred, total } = value
  if (
    typeof percent !== 'number' ||
    !Number.isFinite(percent) ||
    percent < 0 ||
    percent > 100 ||
    typeof bytesPerSecond !== 'number' ||
    !Number.isFinite(bytesPerSecond) ||
    typeof transferred !== 'number' ||
    !Number.isFinite(transferred) ||
    typeof total !== 'number' ||
    !Number.isFinite(total)
  ) {
    return undefined
  }
  return { percent, bytesPerSecond, transferred, total }
}

function readError(value: unknown): UpdateError | undefined {
  if (!isRecord(value)) return undefined
  const code = value.code
  const message = readBoundedString(value.message)
  if (typeof code !== 'string' || !ERROR_CODES.has(code as UpdateErrorCode) || message === undefined) {
    return undefined
  }
  return { code: code as UpdateErrorCode, message, retryable: value.retryable === true }
}

/** Parses the pushed projection at the renderer boundary. Unknown keys are
 *  ignored (forward-compatible: a newer main may add fields), but every
 *  declared field must validate or the whole state is dropped - a
 *  half-valid projection is never rendered. */
export function parseUpdateState(value: unknown): UpdateState | null {
  if (!isRecord(value)) return null
  const phase = value.phase
  if (typeof phase !== 'string' || !PHASES.has(phase as UpdatePhase)) return null
  const currentVersion = readBoundedString(value.currentVersion, 64)
  const currentBuildId = readBoundedString(value.currentBuildId, 128)
  if (currentVersion === undefined || currentBuildId === undefined) return null

  const state: UpdateState = {
    phase: phase as UpdatePhase,
    currentVersion,
    currentBuildId,
  }
  if (value.candidate !== undefined) {
    const candidate = readCandidate(value.candidate)
    if (candidate === undefined) return null
    state.candidate = candidate
  }
  if (value.progress !== undefined) {
    const progress = readProgress(value.progress)
    if (progress === undefined) return null
    state.progress = progress
  }
  if (value.error !== undefined) {
    const error = readError(value.error)
    if (error === undefined) return null
    state.error = error
  }
  return state
}

/** Parses the renderer's install result at the main boundary. The wire
 *  shape is FlushResult: a 'saved' result must carry the committed remote
 *  revision and the admission generation it ran under. */
export function parseUpdateInstallResult(value: unknown): UpdateInstallResult | null {
  if (!isRecord(value)) return null
  const requestId = readBoundedString(value.requestId, 128)
  const generation = value.generation
  const status = value.status
  if (
    requestId === undefined ||
    !Number.isSafeInteger(generation) ||
    (generation as number) < 0 ||
    (status !== 'saved' && status !== 'blocked' && status !== 'failed')
  ) {
    return null
  }
  if (status === 'saved') {
    const revision = value.revision
    if (!Number.isSafeInteger(revision) || (revision as number) < 0) return null
    return { status: 'saved', requestId, generation: generation as number, revision: revision as number }
  }
  const code = readBoundedString(value.code, 128) ?? 'UNKNOWN'
  return { status, requestId, generation: generation as number, code }
}
