<script setup lang="ts">
import { useI18n } from 'vue-i18n'
import SettingsFidelitySection, {type SettingsDisplayControl} from './SettingsFidelitySection.vue'
defineProps<{ groups:readonly {id:string;label:string;controls:readonly SettingsDisplayControl[]}[]; active:string }>()
const emit=defineEmits<{select:[id:string];update:[id:string,value:string|number|boolean];action:[id:string]}>()
const {t}=useI18n()
</script>
<template><div class="settings-layout"><nav :aria-label="t('settingsPreview.title')"><button v-for="id in ['all','audio','display','storage','support']" :key="id" :class="{active:active===id}" @click="emit('select',id)">{{t(`settingsPreview.group.${id}`)}}</button></nav><div class="settings-workspace"><SettingsFidelitySection v-for="group in groups" :key="group.id" :title="group.label" :controls="group.controls" @update="(id,value)=>emit('update',id,value)"/><section v-if="active==='all'||active==='storage'" class="settings-actions"><h2>{{t('settingsPreview.storage')}}</h2><p>{{t('settingsPreview.storageHint')}}</p><div><button v-for="id in ['save','export','import']" :key="id" @click="emit('action',id)">{{t(`settingsPreview.${id}`)}}</button></div></section><section v-if="active==='support'" class="settings-actions"><h2>{{t('settingsPreview.support')}}</h2><p>{{t('settingsPreview.supportHint')}}</p><button @click="emit('action','feedback')">{{t('settingsPreview.feedback')}}</button><p>{{t('settingsPreview.build')}} · {{t('settingsPreview.buildValue')}}</p></section></div></div></template>
<style scoped>.settings-layout { height:100%; display:grid; grid-template-columns:177px 1fr; gap:28px; }.settings-layout nav { display:flex; flex-direction:column; gap:13px; border-right:1px solid #a88b4e66; padding-right:19px; }.settings-layout nav button { padding:12px 10px; border:1px solid #a88b4e; background:linear-gradient(#2b402e,#14281b); color:#e4d0a1; font:16px var(--font-display,Georgia,serif); cursor:pointer; border-radius:3px; }.settings-layout nav button.active { background:linear-gradient(#edd39a,#b7924e); color:#3c290d; box-shadow:0 0 8px #a0803344; font-weight:700; }.settings-workspace { display:flex; flex-direction:column; gap:25px; overflow:auto; scrollbar-width:thin; padding-right:5px; }.settings-actions h2 { margin:0 0 10px; padding-bottom:8px; border-bottom:1px solid #a88b4e66; font-size:18px; }.settings-actions p { margin:8px 0 13px; font-size:13px; color:#76603b; }.settings-actions div { display:flex; gap:15px; }.settings-actions button { padding:9px 22px; border:1px solid #a88b4e; border-radius:3px; background:#263e2b; color:#f3dba3; font:14px var(--font-display,Georgia,serif); cursor:pointer; }button:focus-visible { outline:2px solid #517858; outline-offset:3px; }</style>
