<script setup lang="ts">
export interface SettingsDisplayControl { id:string; label:string; kind:'range'|'toggle'|'select'; value:string|number|boolean; options?:readonly {id:string;label:string}[] }
defineProps<{ title:string; controls:readonly SettingsDisplayControl[] }>()
const emit=defineEmits<{update:[id:string,value:string|number|boolean]}>()
function update(id:string,event:Event,number:boolean) {const target=event.target;if(target instanceof HTMLInputElement||target instanceof HTMLSelectElement)emit('update',id,number?Number(target.value):target.value)}
</script>
<template><section class="settings-section"><h2><span aria-hidden="true">◇</span>{{ title }}</h2><div class="settings-controls"><div v-for="control in controls" :key="control.id" class="settings-control"><label :for="`setting-${control.id}`">{{ control.label }}</label><div class="setting-input"><template v-if="control.kind==='range'"><input :id="`setting-${control.id}`" type="range" min="0" max="100" :value="control.value" @input="update(control.id,$event,true)"><output>{{ control.value }}</output></template><button v-else-if="control.kind==='toggle'" :id="`setting-${control.id}`" class="setting-toggle" role="switch" :aria-checked="Boolean(control.value)" @click="emit('update',control.id,!control.value)"><span/></button><select v-else :id="`setting-${control.id}`" :value="String(control.value)" @change="update(control.id,$event,false)"><option v-for="option in control.options" :key="option.id" :value="option.id">{{ option.label }}</option></select></div></div></div></section></template>
<style scoped>
.settings-section h2 { display:flex; align-items:center; gap:9px; margin:0 0 12px; border-bottom:1px solid #a88b4e66; padding-bottom:8px; color:#493515; font-size:18px; }.settings-section h2 span { width:25px; height:25px; background:#263c2c; border:1px solid #ab8945; color:#e9d19a; text-align:center; }.settings-controls { display:grid; grid-template-columns:1fr 1fr; gap:9px 30px; }.settings-control { display:flex; align-items:center; justify-content:space-between; gap:10px; min-height:30px; font-size:14px; }.setting-input { display:flex; align-items:center; justify-content:flex-end; width:205px; gap:10px; }.setting-input input { width:160px; accent-color:#8f712e; cursor:pointer; }.setting-input output { width:27px; font-size:13px; }.setting-input select { width:185px; padding:5px 8px; border:1px solid #a68847; background:#203629; color:#efdbab; font:13px var(--font-display,Georgia,serif); }.setting-toggle { width:46px; height:23px; padding:2px; border:1px solid #ab8d52; border-radius:15px; background:#3b3f33; cursor:pointer; }.setting-toggle span { display:block; width:17px; height:17px; background:#d2c5a4; border-radius:50%; box-shadow:0 1px 3px #0005; }.setting-toggle[aria-checked=true] { background:#284b37; }.setting-toggle[aria-checked=true] span { margin-left:auto; background:radial-gradient(#fff1ca,#d5b362); }.setting-input :focus-visible { outline:2px solid #517858; outline-offset:3px; }
</style>
