<script setup lang="ts">
import { useI18n } from 'vue-i18n'
import TribulationFidelityFrame from './TribulationFidelityFrame.vue'
import type { TribulationAnswerDisplay } from './tribulationUi'
import CombatFidelityMeter from '@/components/scenes/combat/fidelity/CombatFidelityMeter.vue'
defineProps<{ question: string; answers: readonly TribulationAnswerDisplay[]; selected: string | null; seconds: string; percent: number; notice: string }>()
const emit = defineEmits<{ answer: [id: string] }>()
const { t } = useI18n()
</script>
<template><TribulationFidelityFrame class="question-card"><p class="question-eyebrow">{{ t('mindTrial') }}</p><h2 class="question-text">{{ question }}</h2><div class="answers"><button v-for="(answer, i) in answers" :key="answer.id" :class="{ chosen: answer.id === selected }" :aria-pressed="answer.id === selected" @click="emit('answer', answer.id)"><span class="answer-seal">{{ String.fromCharCode(65 + i) }}</span><span>{{ answer.label }}</span><i aria-hidden="true" class="answer-spark" /></button></div><div class="question-time"><span>{{ t('answerTime') }}</span><strong>{{ seconds }}</strong></div><CombatFidelityMeter :label="t('answerTime')" :value="seconds" :percent="percent" tone="ward" /><p class="question-notice" role="status">{{ notice }}</p></TribulationFidelityFrame></template>
<style scoped>
.question-card { position:absolute; right:31px; top:225px; width:321px; height:408px; padding:28px 24px 20px; pointer-events:auto; }.question-eyebrow { margin:0 0 10px; font-size:12px; letter-spacing:2px; color:#bba273; }.question-text { margin:0 0 20px; height:80px; overflow:auto; font-size:20px; line-height:1.5; font-weight:500; color:#f7e8c7; }.answers { display:flex; flex-direction:column; gap:10px; max-height:185px; overflow:auto; padding:3px; scrollbar-width:thin; }.answers button { display:flex; align-items:center; gap:9px; flex:none; width:100%; min-height:37px; padding:5px 9px 5px 5px; border:1px solid #9a8248; border-radius:4px; background:linear-gradient(90deg,#203026,#0b1712); color:#dfd1ad; text-align:left; font:12px/1.3 var(--font-display,Georgia,serif); cursor:pointer; }.answer-seal { flex:none; display:grid; place-items:center; width:24px; height:24px; border:1px solid #ac8a4d; transform:rotate(45deg); font-size:12px; border-radius:4px; }.answer-spark { flex:none; margin-left:auto; width:8px; height:14px; border:1px solid #ad9764; border-radius:80% 10% 70% 30%; transform:rotate(-35deg); }.answers button.chosen { border-color:#edc56a; background:linear-gradient(90deg,#725022,#253021); color:#fff0c6; box-shadow:inset 0 0 0 2px #bd94472a,0 0 9px #bd944744; }.chosen .answer-spark { background:#ffe7a4; box-shadow:0 0 8px #f7ba40; }.answers button:hover,.answers button:focus-visible { outline:1px solid #f7d584; outline-offset:1px; color:#fff0c6; }.question-time { margin:14px 0 6px; display:flex; justify-content:space-between; font-size:12px; color:#cbb88b; }.question-time strong { color:#f2d890; }.question-notice { margin:8px 0 0; height:30px; font-size:10px; line-height:1.5; color:#d7c59b; }
.question-card { height:480px; }.question-text { height:110px; font-size:18px; line-height:1.5; }.answer-seal { transform:none; border-radius:50%; }
</style>
