// BETA-FINAL PR12 / spec B6 - the packaged update-feed manifest reader.
//
// electron-builder writes resources/app-update.yml from the `publish:`
// block of electron-builder.yml. The UpdateService reads ONLY this file -
// the updater never calls setFeedURL, so this manifest is the feed's
// single authority, and it is verified verbatim against
// EXPECTED_UPDATE_FEED before any check runs. A mismatched manifest means
// the packaged bytes point somewhere we did not build: fail closed.
//
// The file is generated by electron-builder (js-yaml): flat `key: value`
// scalars plus `- item` lists (publisherName can serialize as a list).
// We parse just that subset on purpose - pulling a YAML library into the
// main bundle for 6 known keys is not justified.

import type { UpdateFeedExpectation } from '../shared/update/UpdateState'

/** The feed fields app-update.yml may declare that we care about. */
export interface PackagedFeedConfig {
  provider: string
  owner?: string
  repo?: string
  url?: string
  channel?: string
  publisherName?: string[]
}

/** Parses the flat-scalar/list subset electron-builder emits. Returns
 *  null on anything unreadable or malformed - the caller fails closed. */
export function parsePackagedFeed(text: string): PackagedFeedConfig | null {
  const config: PackagedFeedConfig = { provider: '' }
  const lists = new Map<string, string[]>()
  let currentList: string | null = null

  for (const rawLine of text.split(/\r?\n/)) {
    const line = rawLine.replace(/\s+#.*$/, '')
    if (line.trim() === '') continue

    const listItem = /^\s+-\s+(.*)$/.exec(line)
    if (listItem) {
      if (currentList === null) return null
      lists.get(currentList)!.push(unquote(listItem[1]!.trim()))
      continue
    }

    currentList = null
    const entry = /^([A-Za-z][A-Za-z0-9_]*)\s*:\s*(.*)$/.exec(line.trimStart())
    if (!entry) return null
    const key = entry[1]!
    const value = entry[2]!.trim()

    if (value === '') {
      // `key:` alone opens a block list.
      lists.set(key, [])
      currentList = key
      continue
    }
    if (lists.has(key)) return null // scalar AND list for one key = malformed

    assignField(config, key, unquote(value))
  }

  for (const [key, items] of lists) {
    if (items.length === 0) return null
    assignField(config, key, items)
  }

  return config.provider === '' ? null : config
}

function unquote(value: string): string {
  if (
    (value.startsWith('"') && value.endsWith('"')) ||
    (value.startsWith("'") && value.endsWith("'"))
  ) {
    return value.slice(1, -1)
  }
  return value
}

function assignField(config: PackagedFeedConfig, key: string, value: string | string[]): void {
  const scalar = Array.isArray(value) ? value[0] : value
  switch (key) {
    case 'provider':
      if (Array.isArray(value)) return
      config.provider = value
      return
    case 'owner':
      config.owner = scalar
      return
    case 'repo':
      config.repo = scalar
      return
    case 'url':
      config.url = scalar
      return
    case 'channel':
      config.channel = scalar
      return
    case 'publisherName':
      config.publisherName = Array.isArray(value) ? value : [value]
      return
    default:
      // host/path/updaterCacheDirName etc. - generation details that do
      // not change the trust contract; ignored on purpose.
      return
  }
}

export type FeedVerification =
  | { status: 'ok' }
  | { status: 'invalid'; code: 'FEED_CONFIG_INVALID' | 'WRONG_CHANNEL' | 'PUBLISHER_MISMATCH'; message: string }

/** Verifies the packaged manifest against the expected feed contract. The
 *  check is strict: provider, feed location (owner/repo or https url),
 *  channel and declared publisher must all agree. */
export function verifyPackagedFeed(
  packaged: PackagedFeedConfig | null,
  expected: UpdateFeedExpectation,
): FeedVerification {
  if (packaged === null) {
    return { status: 'invalid', code: 'FEED_CONFIG_INVALID', message: 'no packaged update feed manifest' }
  }
  if (packaged.provider !== expected.provider) {
    return {
      status: 'invalid',
      code: 'FEED_CONFIG_INVALID',
      message: `unexpected update provider: ${packaged.provider}`,
    }
  }
  if (expected.provider === 'github') {
    if (packaged.owner !== expected.owner || packaged.repo !== expected.repo) {
      return {
        status: 'invalid',
        code: 'FEED_CONFIG_INVALID',
        message: 'unexpected update feed repository',
      }
    }
  } else {
    if (packaged.url !== expected.url || (packaged.url ?? '').startsWith('https://') === false) {
      return {
        status: 'invalid',
        code: 'FEED_CONFIG_INVALID',
        message: 'update feed must be the expected https endpoint',
      }
    }
  }

  if (packaged.channel !== expected.channel) {
    return {
      status: 'invalid',
      code: 'WRONG_CHANNEL',
      message: `unexpected update channel: ${packaged.channel ?? 'none'}`,
    }
  }

  // Publisher pinning: while the expected CN is unset (EXT-02 pending),
  // any packaged publisherName is unexpected and rejected rather than
  // silently trusted. Once pinned, the manifest must declare it exactly.
  const declared = packaged.publisherName ?? []
  if (expected.publisherName === null) {
    if (declared.length > 0) {
      return {
        status: 'invalid',
        code: 'PUBLISHER_MISMATCH',
        message: 'packaged feed declares an unexpected publisher',
      }
    }
  } else if (declared.length !== 1 || declared[0] !== expected.publisherName) {
    return {
      status: 'invalid',
      code: 'PUBLISHER_MISMATCH',
      message: 'packaged feed publisher does not match the pinned signer',
    }
  }

  return { status: 'ok' }
}
